(ns re-frame.freehand.manifest-partial-coord-refusal-jvm-test
  "rf2-drpa3.92 — a COMPILED declaration that cannot keep the manifest's
  TOTAL :source-coord promise is refused at expansion, not published
  partial.

  Every compiled-manifest roster entry promises a `:source-coord` of the
  total shape `{:file :line :column}` (rf2-drpa3.82). A `v/defview`
  GENERATED by a wrapper macro carries no reader line/column unless the
  macro copies `(meta &form)` onto the form it emits, so its manifest
  would publish a coordinate whose documented total shape is false —
  which is less honest than refusing the declaration. A wrapper that
  copies the caller form's metadata supplies a truthful call site and is
  accepted unchanged, and an INTERPRETED declaration publishes no manifest
  and so is never refused on this ground.

  The declarations here are SYNTHESIZED forms macroexpanded at runtime
  rather than written at top level, because a top-level generated
  declaration that is refused would fail the namespace's own load — the
  refusal is the point, so it is triggered where it can be caught. The
  metadata a real reader attaches to a source form is modelled explicitly:
  a bare `(list …)` carries none (the generated shape), a `with-meta` form
  carries a line and column (the disciplined wrapper's shape)."
  (:require [clojure.string :as str]
            [clojure.test :refer [deftest is testing]]
            [re-frame.freehand :as v]))

(defn- expand
  "Macroexpand `form` in this namespace's context, answering the thrown
  exception or nil. `*ns*` is bound because macroexpand resolves the head
  against the namespace it runs IN. `macroexpand` wraps a macro's throw in
  a `Compiler$CompilerException`, so the didactic ExceptionInfo is its
  CAUSE — read through [[root]]."
  [form]
  (binding [*ns* (the-ns 're-frame.freehand.manifest-partial-coord-refusal-jvm-test)]
    (try (macroexpand form) nil
         (catch Exception e e))))

(defn- root
  "The ExceptionInfo a macroexpand failure carries, unwrapped from the
  compiler exception that wraps it."
  [ex]
  (or (ex-cause ex) ex))

(deftest a-generated-compiled-defview-without-reader-metadata-is-refused
  (testing "A compiled v/defview whose form carries no reader line/column —
            the shape a wrapper macro emits when it does not preserve
            (meta &form) — is refused at expansion. Its manifest would
            otherwise publish a partial :source-coord whose documented total
            shape is false."
    (let [ex (expand (list `v/defview 'generated-view {:compiled true} '[_] '[:button.audit]))]
      (is (some? ex) "the generated declaration is refused, not accepted")
      (when ex
        (is (= :rf.error/defview-bad-args (:rf.error/id (ex-data (root ex))))
            "it fails at expansion with the declaration diagnostic id")
        (is (str/includes? (ex-message (root ex)) "line/column")
            "the message names the missing half of the coordinate")
        (is (str/includes? (ex-message (root ex)) "meta &form")
            "and the didactic recovery — copy the caller form's metadata")))))

(deftest a-wrapper-that-carries-the-caller-form-metadata-is-accepted
  (testing "A generated declaration whose form carries a truthful line and
            column — the shape a wrapper that copies (meta &form) emits — is
            accepted and compiles. This is the control that makes the
            refusal above mean something: a macroexpansion that failed for an
            unrelated reason would look identical from the catch block."
    (let [form (with-meta (list `v/defview 'anchored-view {:compiled true} '[_] '[:button.audit])
                          {:line 4242 :column 7})]
      (is (nil? (expand form)) "a metadata-carrying compiled declaration is NOT refused")
      (is (seq? (binding [*ns* (the-ns 're-frame.freehand.manifest-partial-coord-refusal-jvm-test)]
                  (macroexpand form)))
          "it expands to a form rather than throwing"))))

(deftest an-interpreted-generated-defview-is-not-refused
  (testing "The refusal is COMPILED-only. An interpreted declaration
            publishes no manifest, so it promises no coordinate and a
            missing reader line/column costs nothing — a wrapper emitting an
            interpreted v/defview stays a reasonable thing to write."
    (is (nil? (expand (list `v/defview 'interpreted-generated '[_] '[:button.audit])))
        "a metadata-less INTERPRETED generated declaration is accepted")
    (is (seq? (binding [*ns* (the-ns 're-frame.freehand.manifest-partial-coord-refusal-jvm-test)]
                (macroexpand (list `v/defview 'interpreted-generated '[_] '[:button.audit]))))
        "and it expands to a form")))
