(ns day8.re-frame2-machines-viz.mermaid
  "Mermaid `stateDiagram-v2` exporter for re-frame2 machine definitions.

  Per `tools/machines-viz/spec/API.md` §Exporters §Mermaid and
  `tools/machines-viz/spec/DESIGN-RATIONALE.md` §Lock #4 (revised
  2026-05-15 per rf2-deo2i — Mermaid emit promoted from v1.1 to v1.0
  as a thin static-topology exporter; rings + `:invoke-all` rows
  remain explicitly out of scope and are flagged in the emitted
  output).

  ## Input

  The `definition` argument is the same normalised machine map the
  framework's `(rf/machine-meta machine-id)` returns — see
  `spec/005-StateMachines.md` §Transition table grammar:

  ```clojure
  {:initial :idle
   :states  {:idle    {:on {:start :loading}}
             :loading {:on {:ok :success :err :failed}}
             :success {:final? true}
             :failed  {:final? true}}}
  ```

  Compound states are supported via nested `:states` + their own
  `:initial`. Final states (`:final? true`) render a terminal
  `--> [*]` edge.

  ## Out of scope (lossy round-trip)

  Mermaid `stateDiagram-v2` cannot express:

  - `:after` countdown rings (timer-driven transitions) — the
    transitions render as plain event-less edges with an `after(...)`
    label, and the omission is flagged in a `%% comment` at the top
    of the emitted block.
  - `:invoke-all` rows of mini-machines — omitted entirely; the
    parent state is rendered without the row, and the omission is
    flagged in the same `%% comment`.
  - Microstep flashes, transition glow, `:tags`, guards, actions —
    none of these are part of the static topology.

  The full topology renders correctly in the SVG / share-URL viewer;
  Mermaid is the Markdown-paste lane only.

  ## Output

  A string containing a fenced markdown code block:

  ```
  ```mermaid
  %% Generated by re-frame2-machines-viz · :after rings + :invoke-all
  %% rows omitted (see SVG / share-URL viewer for full topology)
  stateDiagram-v2
    [*] --> idle
    idle --> loading : start
    loading --> success : ok
    loading --> failed : err
    success --> [*]
    failed --> [*]
  ```
  ```

  The returned string is suitable for paste into a GitHub README,
  a PR description, Notion, or any other Mermaid-aware markdown
  renderer."
  (:require [clojure.string :as str]))

(def ^:private header-comment
  ;; Inserted at the top of every emitted block so a reader who pastes
  ;; the output into a doc sees the lossy-round-trip caveat without
  ;; having to consult the spec.
  (str "%% Generated by re-frame2-machines-viz · :after rings + "
       ":invoke-all rows omitted\n"
       "%% (see SVG / share-URL viewer for full topology)"))

(defn- sanitise-id
  "Map a keyword `id` to a Mermaid-safe identifier.

  Mermaid stateDiagram-v2 identifiers are restricted to a subset of
  alphanumerics + underscore. Namespaced keywords (`:auth/login`) and
  hyphenated names (`:login-flow`) are common in re-frame2 machine
  ids; we map both to underscore-joined names: `:auth/login` →
  `auth_login`, `:login-flow` → `login_flow`."
  [id]
  (when id
    (let [n (name id)
          s (if-let [ns (namespace id)] (str ns "_" n) n)]
      (-> s
          (str/replace #"[^a-zA-Z0-9_]" "_")
          ;; Mermaid identifiers must start with a letter; prefix a
          ;; leading digit with `s_`. (Re-frame2's machine ids
          ;; typically start with a letter; the guard is belt-and-
          ;; braces.)
          (#(if (re-find #"^[0-9]" %) (str "s_" %) %))))))

(defn- sanitise-label
  "Escape a transition event-id for use as a Mermaid edge label.

  Mermaid edge labels live after `: ` to the end of line; newlines
  and the `:` / `\"` characters need taming. Event ids are typically
  keywords (`:submit`, `:rf/load`), printed without the leading
  colon for legibility."
  [event-id]
  (let [s (cond
            (keyword? event-id) (if-let [ns (namespace event-id)]
                                  (str ns "/" (name event-id))
                                  (name event-id))
            :else               (pr-str event-id))]
    (-> s
        (str/replace #"[\r\n]+" " ")
        (str/replace "\"" "'"))))

(defn- transition-target
  "Resolve a transition spec to its target state keyword (or `nil`
  for an action-only / self-transition spec we cannot render).

  Per Spec 005 §Transition table grammar, a transition spec may be:

  - A keyword — the target state.
  - A vector — internal transition with actions, no target.
  - A map — `{:target ... :action ... :guard ...}`; `:target` is the
    target state. Without `:target` the transition is internal (no
    edge).
  - A function — implementation-defined; we cannot statically render
    a fn-shaped transition without running it, so we drop the edge."
  [spec]
  (cond
    (keyword? spec) spec
    (map? spec)     (:target spec)
    :else           nil))

(defn- collect-edges
  "Walk a state node and emit `[from-id event-id to-id]` triples for
  every statically-resolvable transition declared on it.

  Compound states recurse: their substates' edges land in the same
  flat list (Mermaid renders the cross-substate edges fine, and
  compound nesting is handled separately via `render-state-block`)."
  [state-id state-node]
  (let [from-edges
        (for [[event-id spec] (:on state-node)
              :let            [target (transition-target spec)]
              :when           (and target (not= :* event-id))]
          [state-id event-id target])

        nested-edges
        (when (:states state-node)
          (mapcat (fn [[child-id child-node]]
                    (collect-edges child-id child-node))
                  (:states state-node)))]
    (concat from-edges nested-edges)))

(defn- render-edge
  "Render a `[from event to]` triple as a Mermaid edge line."
  [[from event-id to]]
  (str "  " (sanitise-id from) " --> " (sanitise-id to)
       " : " (sanitise-label event-id)))

(defn- render-final-edges
  "Render the `state --> [*]` terminal edges for every `:final?`
  state in the definition (compound-aware)."
  [states]
  (->> states
       (mapcat (fn [[state-id state-node]]
                 (let [self  (when (:final? state-node)
                               [(str "  " (sanitise-id state-id)
                                     " --> [*]")])
                       child (when (:states state-node)
                               (render-final-edges (:states state-node)))]
                   (concat self child))))
       (remove nil?)))

(defn- render-state-block
  "Render a compound state's `state X { ... }` block (Mermaid
  nesting). Returns a sequence of lines (indented at `depth`).

  Leaf states do not need an explicit declaration in Mermaid — they
  appear inline in their outbound edges. We only emit blocks for
  compound states."
  [state-id state-node depth]
  (let [indent     (apply str (repeat depth "  "))
        children   (:states state-node)
        sub-initial (:initial state-node)]
    (when children
      (concat
       [(str indent "state " (sanitise-id state-id) " {")]
       (when sub-initial
         [(str indent "  [*] --> " (sanitise-id sub-initial))])
       (mapcat (fn [[child-id child-node]]
                 (render-state-block child-id child-node (inc depth)))
               children)
       [(str indent "}")]))))

(defn- render-compound-blocks
  "Render every compound state in the top-level `:states` map as a
  Mermaid nested block."
  [states]
  (mapcat (fn [[state-id state-node]]
            (when (:states state-node)
              (render-state-block state-id state-node 1)))
          states))

(defn emit
  "Emit a Mermaid `stateDiagram-v2` string for `definition`.

  Returns a string containing the full fenced markdown code block
  (with the opening ```mermaid and closing ```). Suitable for paste
  into a GitHub README, a PR description, Notion, or any other
  Mermaid-aware renderer.

  Options:

  - `:fenced?` (default `true`) — when `false`, omits the
    ```mermaid / ``` fence and returns just the diagram body. Useful
    when the caller is embedding the diagram inside its own
    markdown wrapper.
  - `:header-comment?` (default `true`) — when `false`, omits the
    `%% Generated by ...` caveat lines. The default-on posture is
    deliberate; a Markdown reader without the caveat may not realise
    `:after` rings are missing.

  Validation: throws `ex-info` with `:reason :invalid-definition`
  if `definition` is missing `:initial` or `:states`."
  ([definition] (emit definition {}))
  ([{:keys [initial states] :as definition}
    {:keys [fenced? header-comment?]
     :or   {fenced?         true
            header-comment? true}}]
   (when-not (and initial (map? states) (seq states))
     (throw (ex-info "definition must carry :initial + non-empty :states"
                     {:reason     :invalid-definition
                      :definition definition})))
   (let [edges        (mapcat (fn [[state-id state-node]]
                                (collect-edges state-id state-node))
                              states)
         edge-lines   (map render-edge edges)
         final-lines  (render-final-edges states)
         compound-lns (render-compound-blocks states)
         body         (str/join "\n"
                                (concat
                                 (when header-comment? [header-comment])
                                 ["stateDiagram-v2"
                                  (str "  [*] --> " (sanitise-id initial))]
                                 compound-lns
                                 edge-lines
                                 final-lines))]
     (if fenced?
       (str "```mermaid\n" body "\n```")
       body))))
