(ns day8.re-frame2-machines-viz.mermaid
  "Mermaid `stateDiagram-v2` exporter for re-frame2 machine definitions.

  Pure-data transform: a machine definition (per Spec 005 §Transition
  table grammar) goes in, a fenced Mermaid markdown block comes out.
  Useful for README docs, PR descriptions, generated reference pages,
  and external rendering pipelines.

  Lives in `tools/machines-viz/` (the read-only visualisation tool),
  not in the runtime `machines` artefact — the Mermaid emitter is a
  tool-side code-gen concern, so the runtime artefact stays
  pure-engine (rf2-sqhqu, Mike-ruled (b) 2026-05-29). Apps that want
  Mermaid require this tool jar; apps that don't pay nothing. (Xray's
  Machine Inspector renders the full live topology; Mermaid is the
  Markdown-paste lane only.)

  ## Input

  The `definition` argument is the same normalised machine map the
  framework's `(rf/machine-meta machine-id)` returns — see
  `spec/005-StateMachines.md` §Transition table grammar:

  ```clojure
  {:initial :idle
   :states  {:idle    {:on {:start :loading}}
             :loading {:on {:ok :success :err :failed}}
             :success {:final? true}
             :failed  {:final? true}}}
  ```

  Compound states are supported via nested `:states` + their own
  `:initial`. Nested Mermaid ids are path-qualified so repeated child
  names under different parents stay distinct. Final states (`:final?
  true`) render a terminal `--> [*]` edge.

  Parallel-region machines (`{:type :parallel :regions ...}`) render
  as a lossy static projection: each region is shown as an independent
  state tree inside a synthetic parallel root. Mermaid cannot express
  the runtime's broadcast macrostep semantics, so the edges are the
  per-region topology only.

  ## Out of scope (lossy round-trip)

  Mermaid `stateDiagram-v2` cannot express:

  - `:after` countdown rings (timer-driven transitions) — the
    transitions render as plain event-less edges with an `after(...)`
    label, and the omission is flagged in a `%% comment` at the top
    of the emitted block.
  - `:spawn-all` rows of mini-machines — omitted entirely; the
    parent state is rendered without the row, and the omission is
    flagged in the same `%% comment`.
  - Microstep flashes, transition glow, `:tags`, guard evaluation,
    actions — none of these are part of the static topology. Guard
    ids still appear on edge labels when present.
  - Parallel-region broadcast macrosteps — regions render, but Mermaid
    does not model the shared one-event/many-regions transition
    semantics.

  The full topology renders correctly in the Xray Machine Inspector;
  Mermaid is the Markdown-paste lane only.

  ## Output

  A string containing a fenced markdown code block:

  ```
  ```mermaid
  %% Generated by day8.re-frame2-machines-viz.mermaid · :after rings +
  %% :spawn-all rows omitted
  %% Parallel regions render as independent static region trees;
  %% broadcast macrostep semantics are lossy
  %% (see Xray Machine Inspector for full topology)
  stateDiagram-v2
    [*] --> idle
    idle --> loading : start
    loading --> success : ok
    loading --> failed : err
    success --> [*]
    failed --> [*]
  ```
  ```

  The returned string is suitable for paste into a GitHub README,
  a PR description, Notion, or any other Mermaid-aware markdown
  renderer."
  (:require [clojure.string :as str]))

(def ^:private header-comment
  ;; Inserted at the top of every emitted block so a reader who pastes
  ;; the output into a doc sees the lossy-round-trip caveat without
  ;; having to consult the spec.
  (str "%% Generated by day8.re-frame2-machines-viz.mermaid · :after rings + "
       ":spawn-all rows omitted\n"
       "%% Parallel regions render as independent static region trees; "
       "broadcast macrostep semantics are lossy\n"
       "%% (see Xray Machine Inspector for full topology)"))

(def ^:private root-fallback-segment :rf.machines-viz.mermaid/root-fallback)
(def ^:private parallel-root-path [:rf.machines-viz.mermaid/parallel-root])

(defn- keyword-label
  "Return a human-readable keyword label without the leading colon."
  [id]
  (if-let [ns (namespace id)]
    (str ns "/" (name id))
    (name id)))

(defn- label-value
  "Return a label string for values that appear on Mermaid edges."
  [v]
  (cond
    (keyword? v) (keyword-label v)
    (string? v)  v
    :else        (pr-str v)))

(defn- target-path?
  "True when `v` is a grammar vector-path target."
  [v]
  (and (vector? v)
       (seq v)
       (every? keyword? v)))

(defn- id-segment
  "Render one path segment before Mermaid-safe character replacement."
  [segment]
  (cond
    (keyword? segment) (let [n (name segment)]
                         (if-let [ns (namespace segment)]
                           (str ns "_" n)
                           n))
    (string? segment)  segment
    (nil? segment)     "nil"
    :else              (pr-str segment)))

(defn- sanitise-id
  "Map a keyword or vector path `id` to a Mermaid-safe identifier.

  Mermaid stateDiagram-v2 identifiers are restricted to a subset of
  alphanumerics + underscore. Namespaced keywords (`:auth/login`) and
  hyphenated names (`:login-flow`) are common in re-frame2 machine
  ids; we map both to underscore-joined names: `:auth/login` →
  `auth_login`, `:login-flow` → `login_flow`.

  Compound state ids are path-qualified with `__` separators:
  `[:authenticated :cart :browsing]` →
  `authenticated__cart__browsing`."
  [id]
  (when id
    (let [segments (if (vector? id) id [id])
          s        (if (seq segments)
                     (str/join "__" (map id-segment segments))
                     "root")]
      (-> s
          (str/replace #"[^a-zA-Z0-9_]" "_")
          ;; Mermaid identifiers must start with a letter; prefix a
          ;; leading digit with `s_`. (Re-frame2's machine ids
          ;; typically start with a letter; the guard is belt-and-
          ;; braces.)
          (#(if (re-find #"^[0-9]" %) (str "s_" %) %))))))

(defn- sanitise-label
  "Escape a transition event-id for use as a Mermaid edge label.

  Mermaid edge labels live after `: ` to the end of line; newlines
  and the `:` / `\"` characters need taming. Event ids are typically
  keywords (`:submit`, `:rf/load`), printed without the leading
  colon for legibility."
  [event-id]
  (let [s (label-value event-id)]
    (-> s
        (str/replace #"[\r\n]+" " ")
        (str/replace "\"" "'"))))

(defn- sanitise-state-label
  "Escape a Mermaid state alias label."
  [label]
  (-> (label-value label)
      (str/replace #"[\r\n]+" " ")
      (str/replace "\"" "'")))

(defn- transition-candidates
  "Normalise a transition spec to candidate maps.

  Per Spec 005 §Transition table grammar, a transition spec may be:

  - A keyword — the target state.
  - A vector path of keywords — an absolute target path from the
    current root (top-level machine root, or parallel-region root).
  - A vector of transition specs — multiple candidates, first-match
    wins at runtime; Mermaid renders every target-bearing branch.
  - A map — `{:target ... :action ... :guard ...}`; `:target` is the
    target state. Without `:target` the transition is internal (no
    edge).
  - A function — implementation-defined; we cannot statically render
    a fn-shaped transition without running it, so we drop the edge."
  [spec]
  (cond
    (keyword? spec)     [{:target spec}]
    (target-path? spec) [{:target spec}]
    (map? spec)         [spec]
    (vector? spec)      (mapcat transition-candidates spec)
    :else               []))

(defn- parent-path
  [path]
  (if (seq path)
    (pop path)
    []))

(defn- resolve-target-path
  "Resolve a transition target against `source-path`.

  Keyword targets are siblings of the source state. Vector-path
  targets are absolute from `root-path`, which is the machine root for
  flat/compound machines and the containing region for parallel
  machines."
  [root-path source-path target]
  (cond
    (= :same-state target) source-path
    (keyword? target)      (conj (parent-path source-path) target)
    (target-path? target)  (into (vec root-path) target)
    :else                  nil))

(defn- guard-suffix
  [candidate]
  (when-let [guard (:guard candidate)]
    (str " [" (sanitise-label guard) "]")))

(defn- edge-label
  ([base candidate] (edge-label base candidate nil))
  ([base candidate suffix]
   (str (sanitise-label base)
        (guard-suffix candidate)
        suffix)))

(defn- collect-transition-edges
  [root-path source-path base-label spec]
  (keep (fn [candidate]
          (when-let [target-path (resolve-target-path root-path
                                                      source-path
                                                      (:target candidate))]
            {:from  source-path
             :to    target-path
             :label (edge-label base-label candidate)}))
        (transition-candidates spec)))

(defn- collect-on-edges
  [root-path source-path on-map]
  (mapcat (fn [[event-id spec]]
            (collect-transition-edges root-path source-path event-id spec))
          on-map))

(defn- collect-after-edges
  [root-path source-path after-map]
  (mapcat (fn [[delay spec]]
            (collect-transition-edges root-path
                                      source-path
                                      (str "after(" (label-value delay) ")")
                                      spec))
          after-map))

(defn- collect-always-edges
  [root-path source-path always]
  (mapcat (fn [candidate]
            (when-let [target-path (resolve-target-path root-path
                                                        source-path
                                                        (:target candidate))]
              [{:from  source-path
                :to    target-path
                :label (edge-label "always" candidate)}]))
          (transition-candidates always)))

(defn- collect-on-done-edges
  "rf2-41goo — emit the compound / region-compound `:on-done` completion
  edge (XState `onDone`). When a compound reaches its `:final?` child the
  engine raises `done.state.<compound>`; the enclosing `:on-done`
  transitions the outer flow. `:on-done` is resolved relative to the
  compound's OWN level (a keyword target is a SIBLING — same level as
  `source-path`), so we resolve against the source's PARENT — exactly the
  ordinary keyword-target rule (`resolve-target-path` already conj's onto
  the parent). The edge is labelled `✓ done` so it reads as the completion
  transition, distinct from an ordinary event arrow. A target-less
  `:on-done` (action/fx-only — the parallel-root shape, handled
  separately) emits no sibling edge here."
  [root-path source-path on-done]
  (keep (fn [candidate]
          (when-let [target-path (resolve-target-path root-path
                                                      source-path
                                                      (:target candidate))]
            {:from  source-path
             :to    target-path
             :label (edge-label "✓ done" candidate)}))
        (transition-candidates on-done)))

(defn- on-done-action-only?
  "rf2-ay42f — true when an `:on-done` spec is ACTION-ONLY: it has at
  least one candidate, and EVERY candidate is target-less (the engine just
  runs an action when the sub-flow completes; the machine stays in the
  all-final config). A target-bearing candidate routes a `✓ done` edge
  (`collect-on-done-edges`); a target-less one has no arrow to draw."
  [on-done]
  (let [cands (transition-candidates on-done)]
    (and (seq cands)
         (every? #(nil? (resolve-target-path [] [] (:target %))) cands))))

(defn- on-done-action-label
  "rf2-ay42f — the `on-done: ✓ done / <action>` note body for an
  action-only `:on-done` (the same caption `render-parallel-on-done-note`
  paints for the parallel-root form). The first candidate's `:action`
  surfaces when present."
  [on-done]
  (let [action (some :action (transition-candidates on-done))]
    (cond-> "on-done: ✓ done"
      action (str " / " (label-value action)))))

(defn- collect-compound-on-done-notes
  "rf2-ay42f — emit a `note right of <compound>` for every COMPOUND state
  whose `:on-done` is ACTION-ONLY (target-less). Mermaid has no
  transitionable completion glyph for an action-only done (there is no
  sibling state to arrow to — the engine just runs the action; the machine
  stays in the all-final config), so — exactly as the PARALLEL-ROOT
  action-only `:on-done` is rendered (`render-parallel-on-done-note`) — we
  render a note carrying `on-done: ✓ done / <action>`.

  Pre-fix, `collect-on-done-edges` kept ONLY target-bearing candidates, so
  a compound action-only `:on-done` (a documented Spec 005 shape — see
  `on-done-edges`' docstring in `chart/layout.cljc`) was SILENTLY DROPPED
  in mermaid while the chart + SCXML emitters surfaced it — breaking the
  G9 'faithful across all three emitters' parity claim. This closes the
  asymmetry: a target-bearing compound `:on-done` routes a `✓ done` edge,
  an action-only one carries a note, so the completion is always visible.

  Walks the state tree the same way `collect-edges` does (compound
  substates recurse), so a deeply-nested compound's action-only completion
  is covered too. Returns a flat seq of note lines."
  [root-path states]
  (mapcat
    (fn [[state-id state-node]]
      (let [state-path (conj (vec root-path) state-id)
            self       (when (and (:states state-node)
                                  (on-done-action-only? (:on-done state-node)))
                         [(str "  note right of " (sanitise-id state-path))
                          (str "    " (on-done-action-label (:on-done state-node)))
                          "  end note"])
            child      (when (:states state-node)
                         (collect-compound-on-done-notes state-path
                                                         (:states state-node)))]
        (concat self child)))
    states))

(defn- collect-root-fallback-edges
  [root-path on-map]
  (let [source-path (conj (vec root-path) root-fallback-segment)]
    (mapcat (fn [[event-id spec]]
              (keep (fn [candidate]
                      (when-let [target-path (resolve-target-path root-path
                                                                  source-path
                                                                  (:target candidate))]
                        {:from  source-path
                         :to    target-path
                         :label (edge-label event-id candidate " (root fallback)")}))
                    (transition-candidates spec)))
            on-map)))

(defn- collect-edges
  "Walk a state node and emit edge maps for
  every statically-resolvable transition declared on it.

  Compound states recurse: their substates' edges land in the same
  flat list (Mermaid renders the cross-substate edges fine, and
  compound nesting is handled separately via `render-state-block`)."
  [root-path state-path state-node]
  (let [from-edges
        (concat
         (collect-on-edges root-path state-path (:on state-node))
         (collect-after-edges root-path state-path (:after state-node))
         (collect-always-edges root-path state-path (:always state-node))
         ;; rf2-41goo — the compound `:on-done` completion edge (sibling
         ;; target). A parallel-root `:on-done` (action/fx-only) is
         ;; rendered separately in `render-parallel-body`.
         (collect-on-done-edges root-path state-path (:on-done state-node)))

        nested-edges
        (mapcat (fn [[child-id child-node]]
                  (collect-edges root-path
                                 (conj state-path child-id)
                                 child-node))
                (:states state-node))]
    (concat from-edges nested-edges)))

(defn- collect-state-map-edges
  [root-path states]
  (mapcat (fn [[state-id state-node]]
            (collect-edges root-path (conj (vec root-path) state-id) state-node))
          states))

(defn- render-edge
  "Render an edge map as a Mermaid edge line."
  [{:keys [from label to]}]
  (str "  " (sanitise-id from) " --> " (sanitise-id to)
       " : " label))

(defn- render-final-edges
  "Render the `state --> [*]` terminal edges for every `:final?`
  state in the definition (compound-aware)."
  [root-path states]
  (->> states
       (mapcat (fn [[state-id state-node]]
                 (let [state-path (conj (vec root-path) state-id)
                       self       (when (:final? state-node)
                                    [(str "  " (sanitise-id state-path)
                                          " --> [*]")])
                       child (when (:states state-node)
                               (render-final-edges state-path (:states state-node)))]
                   (concat self child))))
       (remove nil?)))

(defn- render-state-alias
  [state-path label depth]
  (let [indent (apply str (repeat depth "  "))]
    (str indent "state \"" (sanitise-state-label label) "\" as "
         (sanitise-id state-path))))

(defn- render-state-block
  "Render a compound state's `state X { ... }` block (Mermaid
  nesting). Returns a sequence of lines (indented at `depth`).

  Leaf states do not need an explicit declaration in Mermaid — they
  appear inline in their outbound edges. We only emit blocks for
  compound states."
  [state-path state-node depth]
  (let [indent     (apply str (repeat depth "  "))
        children   (:states state-node)
        sub-initial (:initial state-node)]
    (when children
      (concat
       [(str indent "state " (sanitise-id state-path) " {")]
       (when sub-initial
         [(str indent "  [*] --> " (sanitise-id (conj state-path sub-initial)))])
       (mapcat (fn [[child-id child-node]]
                 (render-state-block (conj state-path child-id)
                                     child-node
                                     (inc depth)))
               children)
       [(str indent "}")]))))

(defn- render-compound-blocks
  "Render every compound state in the top-level `:states` map as a
  Mermaid nested block."
  [root-path states depth]
  (mapcat (fn [[state-id state-node]]
            (when (:states state-node)
              (render-state-block (conj (vec root-path) state-id)
                                  state-node
                                  depth)))
          states))

(defn- render-root-fallback-alias
  [root-path on-map depth]
  (when (seq on-map)
    [(render-state-alias (conj (vec root-path) root-fallback-segment)
                         "root fallback"
                         depth)]))

(defn- render-flat-or-compound-body
  [{:keys [initial states on]} header-comment?]
  (let [root-path      []
        fallback-edges (collect-root-fallback-edges root-path on)
        edges          (concat (collect-state-map-edges root-path states)
                               fallback-edges)
        edge-lines     (map render-edge edges)
        final-lines    (render-final-edges root-path states)
        compound-lines (render-compound-blocks root-path states 1)
        ;; rf2-ay42f — a COMPOUND whose `:on-done` is action-only
        ;; (target-less) has no sibling arrow to draw; render its
        ;; completion as a note so it is not silently dropped (the
        ;; chart + SCXML emitters both surface it).
        on-done-notes  (collect-compound-on-done-notes root-path states)]
    (str/join "\n"
              (concat
               (when header-comment? [header-comment])
               ["stateDiagram-v2"
                (str "  [*] --> " (sanitise-id [initial]))]
               (render-root-fallback-alias root-path on 1)
               compound-lines
               edge-lines
               final-lines
               on-done-notes))))

(defn- region-initial-line
  [region-path initial depth]
  (let [indent (apply str (repeat depth "  "))]
    (str indent "[*] --> " (sanitise-id (conj region-path initial)))))

(defn- render-region-block
  [[region-id {:keys [initial states on] :as _region}]]
  (let [region-path (vector region-id)]
    (concat
     [(str "    state " (sanitise-id region-path) " {")
      (region-initial-line region-path initial 3)]
     (render-root-fallback-alias region-path on 3)
     (render-compound-blocks region-path states 3)
     [(str "    }")])))

(defn- render-parallel-region-blocks
  [regions]
  (mapcat identity
          (interpose ["    --"]
                     (map render-region-block regions))))

(defn- render-parallel-on-done-note
  "rf2-41goo — the PARALLEL-ROOT `:on-done` (XState `onDone` on a parallel
  state). When EVERY region settles `:final?`, the parallel root's
  `:on-done` runs its `:action` + `:fx` (a `:type :parallel` machine is
  root-only — registration rejects a `:target`, so there is no sibling
  state to draw an arrow to; the machine STAYS in the all-final config).
  Mermaid has no transitionable completion glyph for an action-only
  parallel-done, so we render it as a `note` on the parallel root — the
  completion is visible (`✓ done`) with its action when present, without
  inventing a phantom target arrow."
  [on-done]
  (when on-done
    ;; rf2-ay42f — share the `on-done: ✓ done / <action>` caption with the
    ;; COMPOUND action-only note (`on-done-action-label`) so the two
    ;; action-only completion forms read identically.
    [(str "  note right of " (sanitise-id parallel-root-path))
     (str "    " (on-done-action-label on-done))
     "  end note"]))

(defn- render-parallel-body
  [{:keys [regions on on-done]} header-comment?]
  (let [edges       (concat
                     (mapcat (fn [[region-id {:keys [states on]}]]
                               (let [region-path (vector region-id)]
                                 (concat
                                  (collect-state-map-edges region-path states)
                                  (collect-root-fallback-edges region-path on))))
                             regions)
                     (collect-root-fallback-edges [] on))
        edge-lines  (map render-edge edges)
        final-lines (mapcat (fn [[region-id {:keys [states]}]]
                              (render-final-edges [region-id] states))
                            regions)
        ;; rf2-ay42f — a COMPOUND inside a region whose `:on-done` is
        ;; action-only renders the same completion note the flat/compound
        ;; emitter and the parallel-root use (no sibling arrow to draw).
        region-on-done-notes
        (mapcat (fn [[region-id {:keys [states]}]]
                  (collect-compound-on-done-notes [region-id] states))
                regions)]
    (str/join "\n"
              (concat
               (when header-comment? [header-comment])
               ["stateDiagram-v2"
                (str "  [*] --> " (sanitise-id parallel-root-path))]
               (render-root-fallback-alias [] on 1)
               [(str "  state " (sanitise-id parallel-root-path) " {")]
               (render-parallel-region-blocks regions)
               ["  }"]
               edge-lines
               final-lines
               region-on-done-notes
               ;; rf2-41goo — the parallel-root completion note (action/fx-
               ;; only; no sibling target).
               (render-parallel-on-done-note on-done)))))

(defn- valid-state-tree?
  [{:keys [initial states]}]
  (and initial
       (map? states)
       (seq states)))

(defn- parallel-definition?
  [definition]
  (= :parallel (:type definition)))

(defn- valid-parallel-definition?
  [{:keys [regions] :as definition}]
  (and (parallel-definition? definition)
       (map? regions)
       (seq regions)
       (every? valid-state-tree? (vals regions))))

(defn emit
  "Emit a Mermaid `stateDiagram-v2` string for `definition`.

  Returns a string containing the full fenced markdown code block
  (with the opening ```mermaid and closing ```). Suitable for paste
  into a GitHub README, a PR description, Notion, or any other
  Mermaid-aware renderer.

  Options:

  - `:fenced?` (default `true`) — when `false`, omits the
    ```mermaid / ``` fence and returns just the diagram body. Useful
    when the caller is embedding the diagram inside its own
    markdown wrapper.
  - `:header-comment?` (default `true`) — when `false`, omits the
    `%% Generated by ...` caveat lines. The default-on posture is
    deliberate; a Markdown reader without the caveat may not realise
    `:after` rings are missing.

  Validation: throws `ex-info` with `:reason :invalid-definition`
  if a flat/compound definition is missing `:initial` or `:states`,
  or a parallel definition is missing non-empty `:regions` whose
  region bodies each carry `:initial` and `:states`."
  ([definition] (emit definition {}))
  ([definition
    {:keys [fenced? header-comment?]
     :or   {fenced?         true
            header-comment? true}}]
   (let [parallel? (parallel-definition? definition)]
     (when-not (if parallel?
                 (valid-parallel-definition? definition)
                 (valid-state-tree? definition))
       (throw (ex-info (if parallel?
                         "parallel definition must carry non-empty :regions; each region must carry :initial + non-empty :states"
                         "definition must carry :initial + non-empty :states")
                       {:reason     :invalid-definition
                        :definition definition}))))
   (let [body (if (parallel-definition? definition)
                (render-parallel-body definition header-comment?)
                (render-flat-or-compound-body definition header-comment?))]
     (if fenced?
       (str "```mermaid\n" body "\n```")
       body))))
