(ns day8.re-frame2-machines-viz.mermaid
  "Mermaid `stateDiagram-v2` exporter for re-frame2 machine definitions.

  Pure-data transform: a machine definition (per Spec 005 §Transition
  table grammar) goes in, a fenced Mermaid markdown block comes out.
  Useful for README docs, PR descriptions, generated reference pages,
  and external rendering pipelines.

  Lives in `tools/machines-viz/` (the read-only visualisation tool),
  not in the runtime `machines` artefact — the Mermaid emitter is a
  tool-side code-gen concern, so the runtime artefact stays
  pure-engine (rf2-sqhqu, Mike-ruled (b) 2026-05-29). Apps that want
  Mermaid require this tool jar; apps that don't pay nothing. (Xray's
  Machine Inspector renders the full live topology; Mermaid is the
  Markdown-paste lane only.)

  ## Input

  The `definition` argument is the same normalised machine map the
  framework's `(rf/machine-meta machine-id)` returns — see
  `spec/005-StateMachines.md` §Transition table grammar:

  ```clojure
  {:initial :idle
   :states  {:idle    {:on {:start :loading}}
             :loading {:on {:ok :success :err :failed}}
             :success {:final? true}
             :failed  {:final? true}}}
  ```

  Compound states are supported via nested `:states` + their own
  `:initial`. Nested Mermaid ids are path-qualified so repeated child
  names under different parents stay distinct. Final states (`:final?
  true`) render a terminal `--> [*]` edge.

  Parallel-region machines (`{:type :parallel :regions ...}`) render
  as a lossy static projection: each region is shown as an independent
  state tree inside a synthetic parallel root. Mermaid cannot express
  the runtime's broadcast macrostep semantics, so the edges are the
  per-region topology only.

  ## Out of scope (lossy round-trip)

  Mermaid `stateDiagram-v2` cannot express:

  - `:after` countdown rings (timer-driven transitions) — the
    transitions render as plain event-less edges with an `after(...)`
    label, and the omission is flagged in a `%% comment` at the top
    of the emitted block.
  - `:spawn-all` rows of mini-machines — omitted entirely; the
    parent state is rendered without the row, and the omission is
    flagged in the same `%% comment`.
  - Microstep flashes, transition glow, `:tags`, guard evaluation,
    actions — none of these are part of the static topology. Guard
    ids still appear on edge labels when present.
  - Consumer-attachment `:rf.cofx/requires` (EP-0017 — the
    replay-critical host facts a named guard / action consumes;
    rf2-skhlw2.1): INTENTIONALLY OMITTED. Mermaid state-diagram syntax
    has no slot for per-callback coeffect metadata, and an edge label
    carries only `event [guard] / action` (names, never the named-entry
    registry the requirements live on). The interactive MachineChart is
    the EP-0017 'which transitions consume which facts' surface (it paints
    a `needs <id>` chip per guard / action / entry / exit consumer); the
    Markdown-paste lane stays a topology sketch. The omission is locked by
    `mermaid-cljs-test`'s no-cofx-vocabulary regression.
  - Parallel-region broadcast macrosteps — regions render, but Mermaid
    does not model the shared one-event/many-regions transition
    semantics.

  The full topology renders correctly in the Xray Machine Inspector;
  Mermaid is the Markdown-paste lane only.

  ## Output

  A string containing a fenced markdown code block:

  ```
  ```mermaid
  %% Generated by day8.re-frame2-machines-viz.mermaid · :after rings +
  %% :spawn-all rows omitted
  %% Parallel regions render as independent static region trees;
  %% broadcast macrostep semantics are lossy
  %% (see Xray Machine Inspector for full topology)
  stateDiagram-v2
    [*] --> idle
    idle --> loading : start
    loading --> success : ok
    loading --> failed : err
    success --> [*]
    failed --> [*]
  ```
  ```

  The returned string is suitable for paste into a GitHub README,
  a PR description, Notion, or any other Mermaid-aware markdown
  renderer."
  (:require [clojure.string :as str]
            [re-frame.error :as error]
            ;; rf2-b2ygd2 — the SHARED grammar walker + injective id codec
            ;; the three emitters route through, so they address every node
            ;; identically (one escape codec, one source of truth).
            [day8.re-frame2-machines-viz.grammar :as g]))

(def ^:private header-comment
  ;; Inserted at the top of every emitted block so a reader who pastes
  ;; the output into a doc sees the lossy-round-trip caveat without
  ;; having to consult the spec.
  (str "%% Generated by day8.re-frame2-machines-viz.mermaid · :after rings + "
       ":spawn-all rows omitted\n"
       "%% Parallel regions render as independent static region trees; "
       "broadcast macrostep semantics are lossy\n"
       "%% (see Xray Machine Inspector for full topology)"))

(def ^:private root-fallback-segment :rf.machines-viz.mermaid/root-fallback)
(def ^:private parallel-root-path [:rf.machines-viz.mermaid/parallel-root])

;; rf2-b2ygd2 — `keyword-label` is the SHARED fn-tolerant `grammar/name-of`
;; (identical for keywords: `ns/name` or `name`, no leading colon). `label-
;; value` keeps its Mermaid-edge dispatch (string verbatim, else `pr-str`).
(def ^{:arglists '([id])
       :doc "rf2-b2ygd2 — re-export of `grammar/name-of`: a human-readable
  keyword label without the leading colon."}
  keyword-label g/name-of)

(defn- label-value
  "Return a label string for values that appear on Mermaid edges."
  [v]
  (cond
    (keyword? v) (keyword-label v)
    (string? v)  v
    :else        (pr-str v)))

;; rf2-b2ygd2 — grammar walker + injective id codec aliased from the SHARED
;; `grammar` ns (the same `escape-id-segment` the chart `node-id` + the SCXML
;; codec mint, so all three emitters address every node identically —
;; rf2-mnp93.6).
(def ^:private target-path? g/target-path?)
(def ^:private history-node? g/history-node?)
(def ^:private escape-id-segment g/escape-id-segment)

(defn- id-segment
  "Render one path segment as an INJECTIVE Mermaid-id-safe string.

  A keyword's namespace and name are each `escape-id-segment`-escaped
  and joined with `_2f` (the hex escape of `/`, the boundary marker the
  escaper itself uses for a namespaced keyword — so a namespaced keyword
  `:auth/login` reads `auth_2flogin` and can never collide with a state
  literally named `:auth-login` → `auth_2dlogin` (rf2-mnp93.6)."
  [segment]
  (cond
    (keyword? segment) (if-let [ns (namespace segment)]
                         (str (escape-id-segment ns) "_2f" (escape-id-segment (name segment)))
                         (escape-id-segment (name segment)))
    (string? segment)  (escape-id-segment segment)
    (nil? segment)     "nil"
    :else              (escape-id-segment (pr-str segment))))

(defn- sanitise-id
  "Map a keyword or vector path `id` to an INJECTIVE Mermaid-safe
  identifier — distinct inputs always mint distinct ids.

  Mermaid stateDiagram-v2 identifiers are restricted to a subset of
  alphanumerics + underscore. Namespaced keywords (`:auth/login`) and
  hyphenated names (`:login-flow`) are common in re-frame2 machine
  ids. Each path segment is `id-segment`-escaped (every non-alphanumeric
  char → `_<hex>`); compound state ids are path-qualified with `__`
  separators: `[:authenticated :cart :browsing]` →
  `authenticated__cart__browsing`.

  rf2-mnp93.6 — the id is INJECTIVE (the same hex-escape discipline the
  SCXML codec + the chart's xyflow `node-id` follow). The pre-fix naive
  `[^a-zA-Z0-9_]`-collapse merged `:a/b`, `:a-b`, `:a_b` into one node;
  the hex escape keeps them distinct (`a_2fb`, `a_2db`, `a_5fb`). Mermaid
  node-ids are internal — the visible label comes from
  `render-state-alias` — so an injective encoding costs no legibility.
  The id need not start with a letter (Mermaid accepts a leading `_`);
  every escaped non-alphanumeric leader is a `_`, so the prior
  leading-digit `s_` guard is unnecessary (a digit-leading name like
  `:5x` escapes to `_35x` already)."
  [id]
  (when id
    (let [segments (if (vector? id) id [id])]
      (if (seq segments)
        (str/join "__" (map id-segment segments))
        "root"))))

(defn- sanitise-label
  "Escape a transition event-id for use as a Mermaid edge label.

  Mermaid edge labels live after `: ` to the end of line; newlines
  and the `:` / `\"` characters need taming. Event ids are typically
  keywords (`:submit`, `:rf/load`), printed without the leading
  colon for legibility."
  [event-id]
  (let [s (label-value event-id)]
    (-> s
        (str/replace #"[\r\n]+" " ")
        (str/replace "\"" "'"))))

(defn- sanitise-state-label
  "Escape a Mermaid state alias label."
  [label]
  (-> (label-value label)
      (str/replace #"[\r\n]+" " ")
      (str/replace "\"" "'")))

;; rf2-b2ygd2 — the transition-spec walker is the SHARED
;; `grammar/transition-candidates` (chart + per-state SCXML emitters share
;; it). NOTE the parallel-ROOT mermaid path uses its own region-aware
;; exploder (`root-region-qualified-candidates`), mirroring the SCXML
;; `root-transition-candidates` divergence (a vector-of-vectors is one
;; multi-region target, not a candidate fork).
(def ^:private transition-candidates g/transition-candidates)

(def ^:private parent-path g/parent-path)

(defn- resolve-target-path
  "Resolve a transition target against `source-path`.

  Keyword targets are siblings of the source state. Vector-path
  targets are absolute from `root-path`, which is the machine root for
  flat/compound machines and the containing region for parallel
  machines."
  [root-path source-path target]
  (cond
    (= :same-state target) source-path
    (keyword? target)      (conj (parent-path source-path) target)
    (target-path? target)  (into (vec root-path) target)
    :else                  nil))

(defn- guard-suffix
  [candidate]
  (when-let [guard (:guard candidate)]
    (str " [" (sanitise-label guard) "]")))

;; rf2-b2ygd2 — the external-restart predicate is the SHARED
;; `grammar/reenter?` (Spec 005 §Self-transitions / XState v5: a TARGETED
;; transition is INTERNAL by default; only `:reenter? true` makes it
;; external). Without this distinction a `{:target :same-state}` transition
;; charts IDENTICALLY whether or not `:reenter? true` is set.
(def ^:private reenter? g/reenter?)

(defn- reenter-suffix
  "rf2-9dj21r — a trailing `↻` marker on the Mermaid edge label for a
  `:reenter? true` (external restart) transition, so it reads DISTINCTLY
  from its internal-default counterpart (otherwise the two produce
  byte-identical Mermaid)."
  [candidate]
  (when (reenter? candidate)
    " ↻"))

(defn- edge-label
  ([base candidate] (edge-label base candidate nil))
  ([base candidate suffix]
   (str (sanitise-label base)
        (guard-suffix candidate)
        (reenter-suffix candidate)
        suffix)))

(defn- collect-transition-edges
  [root-path source-path base-label spec]
  (keep (fn [candidate]
          (when-let [target-path (resolve-target-path root-path
                                                      source-path
                                                      (:target candidate))]
            {:from  source-path
             :to    target-path
             :label (edge-label base-label candidate)}))
        (transition-candidates spec)))

(defn- collect-on-edges
  [root-path source-path on-map]
  (mapcat (fn [[event-id spec]]
            (collect-transition-edges root-path source-path event-id spec))
          on-map))

(defn- collect-after-edges
  [root-path source-path after-map]
  (mapcat (fn [[delay spec]]
            (collect-transition-edges root-path
                                      source-path
                                      (str "after(" (label-value delay) ")")
                                      spec))
          after-map))

(defn- collect-always-edges
  [root-path source-path always]
  (mapcat (fn [candidate]
            (when-let [target-path (resolve-target-path root-path
                                                        source-path
                                                        (:target candidate))]
              [{:from  source-path
                :to    target-path
                :label (edge-label "always" candidate)}]))
          (transition-candidates always)))

;; --- internal (action-only) transition notes (rf2-mnp93.4) ---------------
;;
;; An INTERNAL transition candidate (a map that OMITS `:target` — Spec 005
;; §Transition slots: "omit for internal"; §Self-transitions: the internal
;; default runs only the `:action`, the config is unchanged) has NO arrow to
;; draw in Mermaid (there is no destination state). Pre-fix, the `:on` /
;; `:after` / `:always` collectors all silently DROPPED every target-less
;; candidate, while the chart + SCXML emitters surfaced it — breaking the G9
;; 'faithful across all three emitters' parity claim
;; (001-Topology-Parity.md §3.1). We close the asymmetry exactly the way the
;; action-only `:on-done` was closed (rf2-ay42f): render the internal
;; transition as a `note right of <state>` so the action it runs is visible.

(defn- internal-candidate?
  "rf2-mnp93.4 — true when a transition candidate is INTERNAL: a map that
  omits `:target` (the action-only / no-config-change shape). A keyword /
  vector-path candidate always carries a target, so only a map can be
  internal."
  [candidate]
  (and (map? candidate)
       (not (contains? candidate :target))))

(defn- internal-note-line
  "rf2-mnp93.4 — the note body for one internal (target-less) candidate.
  Reads `<descriptor> [guard] / <action>` (the same `event [guard] /
  action` order edges use), so an internal `:on :tick {:action :log}`
  surfaces as `on tick / log`, an `:after 1000 {:action :timeout}` as
  `after(1000) / timeout`, an `:always {:action :poll}` as `always / poll`."
  [descriptor candidate]
  (let [guard  (when (:guard candidate)
                 (str " [" (sanitise-label (:guard candidate)) "]"))
        action (when (:action candidate)
                 (str " / " (label-value (:action candidate))))]
    (str "    " (sanitise-label descriptor) guard action)))

(defn- internal-candidate-lines
  "rf2-mnp93.4 — note-body lines for every INTERNAL candidate declared on
  one state's `:on` / `:after` / `:always`. `:on` candidates carry their
  event id as the descriptor; `:after` candidates `after(<delay>)`;
  `:always` candidates `always`."
  [state-node]
  (concat
    (mapcat (fn [[event-id spec]]
              (->> (transition-candidates spec)
                   (filter internal-candidate?)
                   (map #(internal-note-line (label-value event-id) %))))
            (:on state-node))
    (mapcat (fn [[delay spec]]
              (->> (transition-candidates spec)
                   (filter internal-candidate?)
                   (map #(internal-note-line (str "after(" (label-value delay) ")") %))))
            (:after state-node))
    ;; rf2-oy49f1 — gated on `(:always state-node)` being present. `:always`
    ;; is a SINGULAR top-level slot (unlike the per-event `:on`/`:after` maps
    ;; above, where `mapcat` only ever visits a key that EXISTS) — an absent
    ;; `:always` and an explicit nil value are indistinguishable, so
    ;; `transition-candidates`' `(nil? spec) [{}]` forbidden-transition arm
    ;; must not fire here (it would render a phantom "always" note on every
    ;; state with no `:always` declared at all).
    (when (:always state-node)
      (->> (transition-candidates (:always state-node))
           (filter internal-candidate?)
           (map #(internal-note-line "always" %))))))

(defn- collect-internal-transition-notes
  "rf2-mnp93.4 — emit a `note right of <state>` for every state with one or
  more INTERNAL (action-only, target-less) `:on` / `:after` / `:always`
  candidates. Walks the state tree the same way `collect-edges` does so a
  nested state's internal transitions are covered too. Returns a flat seq
  of note lines. Pre-fix these candidates were silently dropped while the
  chart self-anchored them (`:internal? true`) and SCXML emitted them as
  target-less `<transition>`s — this restores three-emitter agreement."
  [root-path states]
  (mapcat
    (fn [[state-id state-node]]
      (let [state-path (conj (vec root-path) state-id)
            lines      (internal-candidate-lines state-node)
            self       (when (seq lines)
                         (concat [(str "  note right of " (sanitise-id state-path))]
                                 lines
                                 ["  end note"]))
            child      (when (:states state-node)
                         (collect-internal-transition-notes state-path
                                                            (:states state-node)))]
        (concat self child)))
    states))

(defn- collect-on-done-edges
  "rf2-41goo — emit the compound / region-compound `:on-done` completion
  edge (XState `onDone`). When a compound reaches its `:final?` child the
  engine raises `done.state.<compound>`; the enclosing `:on-done`
  transitions the outer flow. `:on-done` is resolved relative to the
  compound's OWN level (a keyword target is a SIBLING — same level as
  `source-path`), so we resolve against the source's PARENT — exactly the
  ordinary keyword-target rule (`resolve-target-path` already conj's onto
  the parent). The edge is labelled `✓ done` so it reads as the completion
  transition, distinct from an ordinary event arrow. A target-less
  `:on-done` (action/fx-only — the parallel-root shape, handled
  separately) emits no sibling edge here."
  [root-path source-path on-done]
  (keep (fn [candidate]
          (when-let [target-path (resolve-target-path root-path
                                                      source-path
                                                      (:target candidate))]
            {:from  source-path
             :to    target-path
             :label (edge-label "✓ done" candidate)}))
        (transition-candidates on-done)))

(defn- on-done-action-only?
  "rf2-ay42f — true when an `:on-done` spec is ACTION-ONLY: it has at
  least one candidate, and EVERY candidate is target-less (the engine just
  runs an action when the sub-flow completes; the machine stays in the
  all-final config). A target-bearing candidate routes a `✓ done` edge
  (`collect-on-done-edges`); a target-less one has no arrow to draw.

  rf2-oy49f1 — gated on `on-done` being present. `:on-done` is a SINGULAR
  top-level slot (unlike a per-event `:on`/`:after` MAP entry) — an absent
  `:on-done` and an explicit `nil` value are indistinguishable once
  destructured off the state/region node, so `transition-candidates`'
  `(nil? spec) [{}]` forbidden-transition arm must not fire here (every
  caller of this predicate — `collect-compound-on-done-notes`,
  `region-root-on-done-notes` — invokes it on a state/region that very
  commonly declares NO `:on-done` at all; without this gate EVERY such
  state/region would read as a phantom action-only completion)."
  [on-done]
  (and on-done
       (let [cands (transition-candidates on-done)]
         (and (seq cands)
              (every? #(nil? (resolve-target-path [] [] (:target %))) cands)))))

(defn- on-done-action-label
  "rf2-ay42f — the `on-done: ✓ done / <action>` note body for an
  action-only `:on-done` (the same caption `render-parallel-on-done-note`
  paints for the parallel-root form). The first candidate's `:action`
  surfaces when present."
  [on-done]
  (let [action (some :action (transition-candidates on-done))]
    (cond-> "on-done: ✓ done"
      action (str " / " (label-value action)))))

(defn- collect-compound-on-done-notes
  "rf2-ay42f — emit a `note right of <compound>` for every COMPOUND state
  whose `:on-done` is ACTION-ONLY (target-less). Mermaid has no
  transitionable completion glyph for an action-only done (there is no
  sibling state to arrow to — the engine just runs the action; the machine
  stays in the all-final config), so — exactly as the PARALLEL-ROOT
  action-only `:on-done` is rendered (`render-parallel-on-done-note`) — we
  render a note carrying `on-done: ✓ done / <action>`.

  Pre-fix, `collect-on-done-edges` kept ONLY target-bearing candidates, so
  a compound action-only `:on-done` (a documented Spec 005 shape — see
  `on-done-edges`' docstring in `chart/layout.cljc`) was SILENTLY DROPPED
  in mermaid while the chart + SCXML emitters surfaced it — breaking the
  G9 'faithful across all three emitters' parity claim. This closes the
  asymmetry: a target-bearing compound `:on-done` routes a `✓ done` edge,
  an action-only one carries a note, so the completion is always visible.

  Walks the state tree the same way `collect-edges` does (compound
  substates recurse), so a deeply-nested compound's action-only completion
  is covered too. Returns a flat seq of note lines."
  [root-path states]
  (mapcat
    (fn [[state-id state-node]]
      (let [state-path (conj (vec root-path) state-id)
            self       (when (and (:states state-node)
                                  (on-done-action-only? (:on-done state-node)))
                         [(str "  note right of " (sanitise-id state-path))
                          (str "    " (on-done-action-label (:on-done state-node)))
                          "  end note"])
            child      (when (:states state-node)
                         (collect-compound-on-done-notes state-path
                                                         (:states state-node)))]
        (concat self child)))
    states))

(defn- collect-root-fallback-edges
  [root-path on-map]
  (let [source-path (conj (vec root-path) root-fallback-segment)]
    (mapcat (fn [[event-id spec]]
              (keep (fn [candidate]
                      (when-let [target-path (resolve-target-path root-path
                                                                  source-path
                                                                  (:target candidate))]
                        {:from  source-path
                         :to    target-path
                         :label (edge-label event-id candidate " (root fallback)")}))
                    (transition-candidates spec)))
            on-map)))

(defn- root-region-qualified-candidates
  "rf2-656ivk / rf2-m3otj2 — explode a parallel-ROOT `:on` / `:after`
  candidate carrying a MULTI-region target `{:target [[:a :x] [:b :y]] …}` into
  ONE candidate per region-qualified target (`{:target [:a :x] …}` /
  `{:target [:b :y] …}`), preserving the guard / action / reenter? on each.
  The runtime's root grammar (`re-frame.machines.parallel/normalise-root-
  targets`) treats a vector-of-vectors `:target` as MULTIPLE region targets;
  `resolve-target-path` only resolves a flat keyword-vector path, so without
  this explosion a map-form multi-region root target was SILENTLY DROPPED (the
  pre-fix latent bug in the root `:on` path; rf2-m3otj2 needs it for `:after`
  too). A single-region (`[:a :x]`) or targetless candidate passes through
  unchanged."
  [candidate]
  (let [tgt (:target candidate)]
    (if (and (vector? tgt) (seq tgt) (every? vector? tgt))
      (map #(assoc candidate :target %) tgt)
      [candidate])))

(defn- collect-root-parallel-fallback-edges
  "rf2-656ivk / rf2-m3otj2 — TARGET-BEARING parallel-ROOT `:on` / `:after`
  edges (the ancestor fallback, Spec 005 §Root parallel `:on` / §Root-level
  `:after`). Unlike the REGION-level `collect-root-fallback-edges`, the ROOT's
  targets are REGION-QUALIFIED (`[:a :x]`) — a multi-region candidate
  (`{:target [[:a :x] [:b :y]]}`) is first exploded per region
  (`root-region-qualified-candidates`), then each region-qualified target
  resolves (absolute, from `root-path []`) to the region substate node.
  `base-label` is the event id (`:on`) or `after(<delay>)` (`:after`). An
  ACTION-ONLY candidate (no target) has no arrow — it surfaces as a note
  (`root-fallback-internal-notes`)."
  [root-path source-path base-label spec]
  (->> (transition-candidates spec)
       (mapcat root-region-qualified-candidates)
       (keep (fn [candidate]
               (when-let [target-path (resolve-target-path root-path
                                                           source-path
                                                           (:target candidate))]
                 {:from  source-path
                  :to    target-path
                  :label (edge-label base-label candidate " (root fallback)")})))))

(defn- collect-root-fallback-on-edges
  "rf2-656ivk — the parallel-ROOT's own `:on` ancestor-fallback edges,
  region-qualified-target-aware (multi-region map-form targets included)."
  [root-path on-map]
  (let [source-path (conj (vec root-path) root-fallback-segment)]
    (mapcat (fn [[event-id spec]]
              (collect-root-parallel-fallback-edges root-path source-path event-id spec))
            on-map)))

(defn- collect-root-fallback-after-edges
  "rf2-m3otj2 — the parallel-ROOT's own `:after` ancestor-fallback edges
  (the timer-driven analog), labelled `after(<delay>) … (root fallback)`."
  [root-path after-map]
  (let [source-path (conj (vec root-path) root-fallback-segment)]
    (mapcat (fn [[delay spec]]
              (collect-root-parallel-fallback-edges
                root-path source-path
                (str "after(" (label-value delay) ")")
                spec))
            after-map)))

(defn- root-fallback-internal-notes
  "rf2-656ivk / rf2-m3otj2 — an ACTION-ONLY (target-less) parallel-ROOT `:on` /
  `:after` candidate runs its action and moves NO region (Spec 005 §Root
  parallel `:on` targetless form / §Root-level `:after` action-only form). It
  has no arrow to draw, so — exactly as F2/F5 surface an action-only
  `:on-done` / internal transition — render it as a `note right of <parallel
  root>` so the affordance is not silently dropped (the chart self-anchors it
  `:internal?`; SCXML emits a target-less `<transition>`). Returns a flat seq
  of note lines (empty when there is nothing internal to surface)."
  [on-map after-map]
  (let [on-lines
        (mapcat (fn [[event-id spec]]
                  (->> (transition-candidates spec)
                       (filter internal-candidate?)
                       (map #(internal-note-line (label-value event-id) %))))
                on-map)
        after-lines
        (mapcat (fn [[delay spec]]
                  (->> (transition-candidates spec)
                       (filter internal-candidate?)
                       (map #(internal-note-line (str "after(" (label-value delay) ")") %))))
                after-map)
        lines (concat on-lines after-lines)]
    (when (seq lines)
      (concat [(str "  note right of " (sanitise-id parallel-root-path))]
              lines
              ["  end note"]))))

(defn- collect-edges
  "Walk a state node and emit edge maps for
  every statically-resolvable transition declared on it.

  Compound states recurse: their substates' edges land in the same
  flat list (Mermaid renders the cross-substate edges fine, and
  compound nesting is handled separately via `render-state-block`)."
  [root-path state-path state-node]
  (let [from-edges
        (concat
         (collect-on-edges root-path state-path (:on state-node))
         (collect-after-edges root-path state-path (:after state-node))
         (collect-always-edges root-path state-path (:always state-node))
         ;; rf2-41goo — the compound `:on-done` completion edge (sibling
         ;; target). A parallel-root `:on-done` (action/fx-only) is
         ;; rendered separately in `render-parallel-body`.
         (collect-on-done-edges root-path state-path (:on-done state-node)))

        nested-edges
        (mapcat (fn [[child-id child-node]]
                  (collect-edges root-path
                                 (conj state-path child-id)
                                 child-node))
                (:states state-node))]
    (concat from-edges nested-edges)))

(defn- collect-state-map-edges
  [root-path states]
  (mapcat (fn [[state-id state-node]]
            (collect-edges root-path (conj (vec root-path) state-id) state-node))
          states))

(defn- render-edge
  "Render an edge map as a Mermaid edge line."
  [{:keys [from label to]}]
  (str "  " (sanitise-id from) " --> " (sanitise-id to)
       " : " label))

(defn- render-final-edges
  "Render the `state --> [*]` terminal edges for every `:final?`
  state in the definition (compound-aware)."
  [root-path states]
  (->> states
       (mapcat (fn [[state-id state-node]]
                 (let [state-path (conj (vec root-path) state-id)
                       self       (when (:final? state-node)
                                    [(str "  " (sanitise-id state-path)
                                          " --> [*]")])
                       child (when (:states state-node)
                               (render-final-edges state-path (:states state-node)))]
                   (concat self child))))
       (remove nil?)))

(defn- render-error-final-notes
  "EP-0011 — visibly mark every `:final? true :error? true` ERROR terminal
  (compound-aware). Spec 005 §`:final?` lets a final leaf carry `:error?
  true`: a child finishing via an error final lowers to the uniform reply
  envelope as `:status :error` and routes the spawning parent's `:spawn`
  `:on-error` (vs a plain final's `:status :ok` / `:on-done`). This is a
  re-frame2 routing distinction the FRAMEWORK acts on, not decoration.

  Mermaid's `[*]` terminal has no error-terminal glyph, so — same posture
  as the action-only / history annotations — the distinction is surfaced
  visibly via a `note right of <error-final>` rather than collapsing into a
  plain success terminal. A plain `:final?` (success) terminal carries NO
  such note. (The chart canvas paints the error-hue ring; the SCXML emitter
  carries `data_rf_error_final`; this is the Mermaid surface's counterpart.)"
  [root-path states]
  (mapcat
    (fn [[state-id state-node]]
      (let [state-path (conj (vec root-path) state-id)
            self       (when (and (:final? state-node) (:error? state-node))
                         [(str "  note right of " (sanitise-id state-path))
                          ;; EP-0011 — names the completion KIND + the
                          ;; parent routing it drives, so a reader sees this
                          ;; is not a success terminal.
                          "    error terminal — completes :status :error (parent :on-error)"
                          "  end note"])
            child      (when (:states state-node)
                         (render-error-final-notes state-path (:states state-node)))]
        (concat self child)))
    states))

(defn- render-state-alias
  [state-path label depth]
  (let [indent (apply str (repeat depth "  "))]
    (str indent "state \"" (sanitise-state-label label) "\" as "
         (sanitise-id state-path))))

(defn- render-history-marker
  "rf2-m285a — declare a `:type :history` pseudo-state inside its owning
  compound block (Spec 005 §History states). Mermaid `stateDiagram-v2`
  has no portable native history glyph (the `[H]` form is spottily
  rendered across Mermaid versions / consumers), so — same lossy-static
  posture the emitter takes elsewhere — we declare a labelled alias node
  (`H` shallow / `H*` deep) so incoming `:target :hist` edges land on a
  node that READS as a history marker, not an ordinary state. A
  `:default-target` rides a `%% comment` so the default config is visible
  without re-running the machine."
  [state-path state-node depth]
  (let [indent (apply str (repeat depth "  "))
        glyph  (if (:deep? state-node) "H*" "H")
        dt     (:default-target state-node)]
    (cond-> [(str indent "state \"" glyph "\" as " (sanitise-id state-path))]
      (some? dt)
      (conj (str indent "%% history default-target: "
                 (if (vector? dt)
                   (str/join "/" (map keyword-label dt))
                   (label-value dt)))))))

(defn- render-state-block
  "Render a compound state's `state X { ... }` block (Mermaid
  nesting). Returns a sequence of lines (indented at `depth`).

  Leaf states do not need an explicit declaration in Mermaid — they
  appear inline in their outbound edges. We only emit blocks for
  compound states.

  rf2-m285a — a `:type :history` child is declared as a labelled history
  marker (`render-history-marker`) so an incoming `:target :hist` edge
  lands on a node that reads as a history pseudo-state."
  [state-path state-node depth]
  (let [indent     (apply str (repeat depth "  "))
        children   (:states state-node)
        sub-initial (:initial state-node)]
    (when children
      (concat
       [(str indent "state " (sanitise-id state-path) " {")]
       (when sub-initial
         [(str indent "  [*] --> " (sanitise-id (conj state-path sub-initial)))])
       (mapcat (fn [[child-id child-node]]
                 (let [child-path (conj state-path child-id)]
                   (if (history-node? child-node)
                     (render-history-marker child-path child-node (inc depth))
                     (render-state-block child-path
                                         child-node
                                         (inc depth)))))
               children)
       [(str indent "}")]))))

(defn- render-compound-blocks
  "Render every compound state in the top-level `:states` map as a
  Mermaid nested block."
  [root-path states depth]
  (mapcat (fn [[state-id state-node]]
            (when (:states state-node)
              (render-state-block (conj (vec root-path) state-id)
                                  state-node
                                  depth)))
          states))

(defn- render-root-fallback-alias
  "Declare the `root fallback` alias state — the source node every root /
  region top-level fallback edge hangs off. rf2-m3otj2 — also declared when a
  parallel-root `:after` (the timer-driven fallback) is present, so its
  `after(<delay>)` edge sources from the SAME labelled node, not an
  auto-created bare one. `after-map` is optional (region-level fallbacks pass
  only an `:on`)."
  ([root-path on-map depth] (render-root-fallback-alias root-path on-map nil depth))
  ([root-path on-map after-map depth]
   (when (or (seq on-map) (seq after-map))
     [(render-state-alias (conj (vec root-path) root-fallback-segment)
                          "root fallback"
                          depth)])))

(defn- flat-root-fallback-internal-notes
  "rf2-5uhdaz — an ACTION-ONLY (target-less) machine-level (top-level) `:on`
  fallback runs its action and leaves the state unchanged (Spec 005 — the
  root `:on` is consulted last by `re-frame.machines.transition/pick-
  transition`; XState v5 targetless-transition semantics). It has no arrow to
  draw, so — exactly as the parallel-ROOT `root-fallback-internal-notes` and
  the per-state `collect-internal-transition-notes` do — surface it as a
  `note right of <root fallback>` so the inherited fallback ACTION is not
  silently dropped (the chart self-anchors it `:internal?` on the machine-root
  chip). Returns a flat seq of note lines (empty when nothing is internal)."
  [on-map]
  (let [lines (mapcat (fn [[event-id spec]]
                        (->> (transition-candidates spec)
                             (filter internal-candidate?)
                             (map #(internal-note-line (label-value event-id) %))))
                      on-map)]
    (when (seq lines)
      (concat [(str "  note right of "
                    (sanitise-id [root-fallback-segment]))]
              lines
              ["  end note"]))))

(defn- region-fallback-internal-notes
  "rf2-pdvtxt — an ACTION-ONLY (target-less) REGION-level top-level `:on`
  fallback (`:on {:abort {:action :log}}` on a region map) runs its action and
  moves no state. Like the flat machine's `flat-root-fallback-internal-notes`
  and the parallel-root's `root-fallback-internal-notes`, it has no arrow to
  draw, so it must surface as a `note right of <region root fallback>` — the
  region's own `root fallback` alias node (`render-region-block` already
  declares it whenever the region carries a top-level `:on`).

  Pre-fix this candidate was silently dropped from EVERY collector in
  `render-parallel-body`: `collect-root-fallback-edges` emits only when a
  target resolves (so a targetless region `:on` produced no edge); the
  per-region `region-internal-notes` walk only descends the region's STATES,
  not the region's OWN top-level `:on`; and `root-internal-notes` handles the
  parallel-ROOT's `:on`/`:after`, not each region's. The chart self-anchors
  this fallback `:internal?` on the region container and SCXML emits a
  target-less `<transition>`, so dropping it broke three-emitter agreement.
  Returns a flat seq of note lines (empty when no region has a targetless
  top-level fallback)."
  [regions]
  (mapcat
    (fn [[region-id {:keys [on]}]]
      (let [lines (mapcat (fn [[event-id spec]]
                            (->> (transition-candidates spec)
                                 (filter internal-candidate?)
                                 (map #(internal-note-line (label-value event-id) %))))
                          on)]
        (when (seq lines)
          (concat [(str "  note right of "
                        (sanitise-id [region-id root-fallback-segment]))]
                  lines
                  ["  end note"]))))
    regions))

(defn- render-flat-or-compound-body
  [{:keys [initial states on]} header-comment?]
  (let [root-path      []
        fallback-edges (collect-root-fallback-edges root-path on)
        edges          (concat (collect-state-map-edges root-path states)
                               fallback-edges)
        edge-lines     (map render-edge edges)
        final-lines    (render-final-edges root-path states)
        ;; EP-0011 — mark error-final terminals (`:final? true :error? true`)
        ;; so their `:status :error` / parent `:on-error` routing is not
        ;; silently collapsed into a plain success terminal.
        error-final-notes (render-error-final-notes root-path states)
        compound-lines (render-compound-blocks root-path states 1)
        ;; rf2-ay42f — a COMPOUND whose `:on-done` is action-only
        ;; (target-less) has no sibling arrow to draw; render its
        ;; completion as a note so it is not silently dropped (the
        ;; chart + SCXML emitters both surface it).
        on-done-notes  (collect-compound-on-done-notes root-path states)
        ;; rf2-mnp93.4 — an INTERNAL (action-only, target-less) `:on` /
        ;; `:after` / `:always` candidate has no arrow to draw; render it
        ;; as a note so it is not silently dropped (the chart self-anchors
        ;; it `:internal? true`, SCXML emits a target-less <transition>).
        internal-notes (collect-internal-transition-notes root-path states)
        ;; rf2-5uhdaz — a targetless machine-level (top-level) `:on` fallback
        ;; is likewise action-only; surface it as a note on the `root fallback`
        ;; alias (the chart self-anchors it on the machine-root chip).
        root-fallback-notes (flat-root-fallback-internal-notes on)]
    (str/join "\n"
              (concat
               (when header-comment? [header-comment])
               ["stateDiagram-v2"
                (str "  [*] --> " (sanitise-id [initial]))]
               (render-root-fallback-alias root-path on 1)
               compound-lines
               edge-lines
               final-lines
               error-final-notes
               on-done-notes
               internal-notes
               root-fallback-notes))))

(defn- region-initial-line
  [region-path initial depth]
  (let [indent (apply str (repeat depth "  "))]
    (str indent "[*] --> " (sanitise-id (conj region-path initial)))))

(defn- render-region-block
  [[region-id {:keys [initial states on] :as _region}]]
  (let [region-path (vector region-id)]
    (concat
     [(str "    state " (sanitise-id region-path) " {")
      (region-initial-line region-path initial 3)]
     (render-root-fallback-alias region-path on 3)
     (render-compound-blocks region-path states 3)
     [(str "    }")])))

(defn- render-parallel-region-blocks
  [regions]
  (mapcat identity
          (interpose ["    --"]
                     (map render-region-block regions))))

(defn- render-parallel-on-done-note
  "rf2-41goo — the PARALLEL-ROOT `:on-done` (XState `onDone` on a parallel
  state). When EVERY region settles `:final?`, the parallel root's
  `:on-done` runs its `:action` + `:fx` (a `:type :parallel` machine is
  root-only — registration rejects a `:target`, so there is no sibling
  state to draw an arrow to; the machine STAYS in the all-final config).
  Mermaid has no transitionable completion glyph for an action-only
  parallel-done, so we render it as a `note` on the parallel root — the
  completion is visible (`✓ done`) with its action when present, without
  inventing a phantom target arrow."
  [on-done]
  (when on-done
    ;; rf2-ay42f — share the `on-done: ✓ done / <action>` caption with the
    ;; COMPOUND action-only note (`on-done-action-label`) so the two
    ;; action-only completion forms read identically.
    [(str "  note right of " (sanitise-id parallel-root-path))
     (str "    " (on-done-action-label on-done))
     "  end note"]))

(defn- region-root-on-done-edges
  "rf2-f8fgz5 — a REGION's OWN top-level `:on-done` (Spec 005 §Parallel
  `:on-done`: 'A **compound region** reaching its own `:final?` child
  raises a region-local `done.state.<region-compound>` that the region's
  `:on-done` takes … exactly the compound case, scoped to one region').
  Reuses `collect-on-done-edges` — the SAME walker a nested compound's
  `:on-done` uses — with the region's OWN container path doubling as both
  `root-path` and `source-path` (the done-source). A KEYWORD target is
  therefore a SIBLING OF THE REGION (another key in `:regions`), exactly
  as a nested compound's keyword `:on-done` target is a sibling of the
  compound — empirically verified against `scxml.cljc`'s `emit-state`
  (which reads `:on-done` off ANY state node, a region included, via the
  same sibling-resolution rule: a 2-region probe with `:on-done :b` on
  region `:a` emits `<transition event=\"done.state.a\" target=\"b\"/>`,
  `b` being the SIBLING region's own qualified id). A vector-path target
  resolves IN-REGION (prefixed with the region id via `root-path`),
  matching every other region-level collector in this namespace
  (`collect-root-fallback-edges` et al).

  Pre-fix `render-region-block` destructured only `{:keys [initial states
  on]}` — never `:on-done` — so a target-bearing region `:on-done`
  vanished from Mermaid with zero trace while SCXML preserved the
  `done.state.<region> -> <sibling-region>` transition, breaking the G9
  cross-emitter parity invariant (001-Topology-Parity.md)."
  [regions]
  (mapcat (fn [[region-id {:keys [on-done]}]]
            (let [region-path (vector region-id)]
              (collect-on-done-edges region-path region-path on-done)))
          regions))

(defn- region-root-on-done-notes
  "rf2-f8fgz5 — the ACTION-ONLY counterpart of `region-root-on-done-
  edges`: a region's own top-level `:on-done` with no resolvable target
  has no sibling-region arrow to draw, so — exactly as
  `collect-compound-on-done-notes` renders a nested compound's
  action-only `:on-done` (and `render-parallel-on-done-note` renders the
  parallel-root's) — it surfaces as a `note right of` the region's OWN
  container (the region root)."
  [regions]
  (mapcat (fn [[region-id {:keys [on-done]}]]
            (when (on-done-action-only? on-done)
              [(str "  note right of " (sanitise-id [region-id]))
               (str "    " (on-done-action-label on-done))
               "  end note"]))
          regions))

(defn- render-parallel-body
  [{:keys [regions on after on-done]} header-comment?]
  (let [edges       (concat
                     (mapcat (fn [[region-id {:keys [states on]}]]
                               (let [region-path (vector region-id)]
                                 (concat
                                  (collect-state-map-edges region-path states)
                                  (collect-root-fallback-edges region-path on))))
                             regions)
                     ;; rf2-656ivk — the parallel-ROOT's own `:on` uses the
                     ;; region-qualified-target-aware collector (a multi-region
                     ;; map-form target `{:target [[:a :x] [:b :y]]}` was
                     ;; SILENTLY DROPPED by the region-level collector's
                     ;; flat-path-only `resolve-target-path`).
                     (collect-root-fallback-on-edges [] on)
                     ;; rf2-m3otj2 — the parallel-ROOT's own `:after` (the
                     ;; timer-driven ancestor fallback) renders as a root-
                     ;; fallback edge labelled `after(<delay>)`. Pre-fix the
                     ;; root `:after` was DROPPED entirely (destructured only
                     ;; `regions on on-done`).
                     (collect-root-fallback-after-edges [] after)
                     ;; rf2-f8fgz5 — a REGION's OWN top-level `:on-done`
                     ;; (target-bearing form): a `✓ done` edge to the
                     ;; SIBLING region. Pre-fix `render-region-block`
                     ;; destructured only `{:keys [initial states on]}`, so
                     ;; this vanished from Mermaid while SCXML preserved it.
                     (region-root-on-done-edges regions))
        edge-lines  (map render-edge edges)
        final-lines (mapcat (fn [[region-id {:keys [states]}]]
                              (render-final-edges [region-id] states))
                            regions)
        ;; EP-0011 — mark error-final terminals inside any region so the
        ;; `:status :error` / parent `:on-error` routing is not silently
        ;; collapsed into a plain success terminal (matches the flat/
        ;; compound emitter).
        error-final-notes
        (mapcat (fn [[region-id {:keys [states]}]]
                  (render-error-final-notes [region-id] states))
                regions)
        ;; rf2-ay42f — a COMPOUND inside a region whose `:on-done` is
        ;; action-only renders the same completion note the flat/compound
        ;; emitter and the parallel-root use (no sibling arrow to draw).
        region-on-done-notes
        (mapcat (fn [[region-id {:keys [states]}]]
                  (collect-compound-on-done-notes [region-id] states))
                regions)
        ;; rf2-f8fgz5 — a REGION's OWN top-level `:on-done` (action-only
        ;; form): no sibling-region arrow to draw, so it surfaces as a
        ;; note on the region's own container (the region root).
        region-root-on-done-note-lines (region-root-on-done-notes regions)
        ;; rf2-mnp93.4 — an INTERNAL (action-only) `:on` / `:after` /
        ;; `:always` candidate on a state inside a region renders as a note
        ;; too (no arrow to draw), matching the flat/compound emitter.
        region-internal-notes
        (mapcat (fn [[region-id {:keys [states]}]]
                  (collect-internal-transition-notes [region-id] states))
                regions)
        ;; rf2-656ivk / rf2-m3otj2 — an ACTION-ONLY parallel-root `:on` /
        ;; `:after` candidate (runs an action, moves no region) has no arrow
        ;; to draw; surface it as a note on the parallel root so it is not
        ;; silently dropped (pre-fix the action-only root `:on` was dropped by
        ;; `collect-root-fallback-edges`' target `when-let`; the root `:after`
        ;; was never collected at all).
        root-internal-notes (root-fallback-internal-notes on after)
        ;; rf2-pdvtxt — an ACTION-ONLY REGION-level top-level `:on` fallback
        ;; (`:on {:abort {:action :log}}` on a region) is likewise target-less;
        ;; surface it as a note on that region's `root fallback` alias. Pre-fix
        ;; it fell through every collector above (the targetless region `:on`
        ;; produced no edge, and neither the per-region state walk nor the
        ;; parallel-root note helper covered the region's OWN top-level `:on`).
        region-fallback-notes (region-fallback-internal-notes regions)]
    (str/join "\n"
              (concat
               (when header-comment? [header-comment])
               ["stateDiagram-v2"
                (str "  [*] --> " (sanitise-id parallel-root-path))]
               (render-root-fallback-alias [] on after 1)
               [(str "  state " (sanitise-id parallel-root-path) " {")]
               (render-parallel-region-blocks regions)
               ["  }"]
               edge-lines
               final-lines
               error-final-notes
               region-on-done-notes
               region-root-on-done-note-lines
               region-internal-notes
               region-fallback-notes
               root-internal-notes
               ;; rf2-41goo — the parallel-root completion note (action/fx-
               ;; only; no sibling target).
               (render-parallel-on-done-note on-done)))))

;; rf2-egupfk — the definition-shape validators + value-free summary are the
;; SHARED grammar helpers (`grammar/valid-definition?` / `parallel-definition?`
;; / `definition-summary`), so all three emitters agree on which definitions
;; are projectable (keyword `:initial`, well-formed parallel regions) and on
;; the value-free error diagnostic. Mermaid keeps only its surface-specific
;; error id (`:mermaid/invalid-definition`) + message below.

(defn emit
  "Emit a Mermaid `stateDiagram-v2` string for `definition`.

  Returns a string containing the full fenced markdown code block
  (with the opening ```mermaid and closing ```). Suitable for paste
  into a GitHub README, a PR description, Notion, or any other
  Mermaid-aware renderer.

  Options:

  - `:fenced?` (default `true`) — when `false`, omits the
    ```mermaid / ``` fence and returns just the diagram body. Useful
    when the caller is embedding the diagram inside its own
    markdown wrapper.
  - `:header-comment?` (default `true`) — when `false`, omits the
    `%% Generated by ...` caveat lines. The default-on posture is
    deliberate; a Markdown reader without the caveat may not realise
    `:after` rings are missing.

  Validation: throws `ex-info` with `:reason :invalid-definition`
  if a flat/compound definition is missing `:initial` or `:states`,
  or a parallel definition is missing non-empty `:regions` whose
  region bodies each carry `:initial` and `:states`."
  ([definition] (emit definition {}))
  ([definition
    {:keys [fenced? header-comment?]
     :or   {fenced?         true
            header-comment? true}}]
   ;; EP-0029 — lower the named-intent grammars before rendering: `:timeout`
   ;; / `:on-timeout` → `:after` (A4, surfaces as an `after / …` edge label)
   ;; and `:type :choice` / `:choice` → `:always` (A5, surfaces the
   ;; candidate edges). Bind once so BOTH the validation block and the
   ;; render below see the lowered form.
   (let [definition (g/desugar-grammar definition)
         parallel?  (g/parallel-definition? definition)]
     (when-not (g/valid-definition? definition)
       (error/throw-error!
         :mermaid/invalid-definition
         'machines-viz.mermaid/emit
         (if parallel?
           (str "Mermaid export: a parallel definition must carry a non-empty "
                ":regions map, and each region must carry a keyword :initial + "
                "a non-empty :states map. Provide those.")
           (str "Mermaid export: a definition must carry a keyword :initial + "
                "a non-empty :states map. Provide those."))
         {:recovery :supply-a-valid-definition
          ;; rf2-8nzxib — value-FREE; never the raw definition (its
          ;; :data slot can hold live runtime values).
          :extra    {:definition-summary (g/definition-summary definition)}}))
     (let [body (if parallel?
                  (render-parallel-body definition header-comment?)
                  (render-flat-or-compound-body definition header-comment?))]
       (if fenced?
         (str "```mermaid\n" body "\n```")
         body)))))
