(ns re-frame.ssr-boolean-attr-react-parity-test
  "rf2-r9kf (second pass) — the SSR boolean attribute-value rosters pinned
  against react-dom ITSELF, not against another re-frame serialiser.

  WHY THIS FILE EXISTS, AND WHY `ssr_emit_test`'s parity deftest could not
  do its job. The first pass gave the hiccup emitter and the structural-tree
  serialiser ONE shared classifier (`html-helpers/boolean-attr-class`). That
  removed the drift between them — and with it the only check that had been
  watching. A parity test between two CONSUMERS of a shared table cannot
  validate the table: both sides read the same rosters, so both are wrong in
  the same way and agree. The post-merge audit found exactly that. The
  classifier was internally consistent and still missing eight names —
  `disablePictureInPicture`, `disableRemotePlayback`, `scoped`, `seamless`
  (presence) and `autoReverse`, `externalResourcesRequired`, `focusable`,
  `preserveAlpha` (stringifying) — with every in-repo test green.

  Only something OUTSIDE the shared source can catch that, so the evidence
  here is react-dom's own output:

    `react_dom_probe/boolean_attr_classes.cjs` renders every boolean-valued
    attribute react-dom accepts, against the INSTALLED react-dom, and writes
    the resulting markup to `react_dom_probe/boolean_attr_classes.edn`. Both
    halves are React's — the candidate names are the values of react-dom's
    own `possibleStandardNames` table, and \"is this a boolean attribute?\"
    is React's own development-build warning rather than our opinion. Taking
    the candidate list from our roster would have reproduced the blind spot
    exactly: a name missing from the roster would be missing from the probe.

  This namespace reads that EDN, DERIVES the class from React's bytes in
  Clojure, and compares it with `boolean-attr-class` in BOTH directions — a
  name React classifies that we do not, and a name we classify that React
  does not, both red. Two rows are documented divergences rather than bugs
  (`value` and `ismap`); they are named below with their reasons, and each is
  pinned so that the premise reding is itself a failure.

  Then it drives every row through the PUBLIC emitters — `emit/
  render-to-string`, `streaming/render-shell`, and `ui-tree/emit-ui-tree` —
  so the roster being right cannot be undone by a serialiser that stops
  consulting it.

  The fixture is committed and regenerated by hand (the JVM suite must not
  need `node_modules`); the header of the `.edn` carries the command."
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.string :as str]
            [clojure.test :refer [deftest is testing use-fixtures]]
            [re-frame.ssr.emit :as rf.ssr.emit]
            [re-frame.ssr.html-helpers :as rf.ssr.html-helpers]
            [re-frame.ssr.streaming :as rf.ssr.streaming]
            [re-frame.ssr.test-fixture :as rf.ssr.test-fixture]
            [re-frame.ssr.ui-tree :as rf.ssr.ui-tree]))

(use-fixtures :each rf.ssr.test-fixture/reset-runtime)

;; ---------------------------------------------------------------------------
;; The external evidence.
;; ---------------------------------------------------------------------------

(def ^:private fixture-resource
  "react_dom_probe/boolean_attr_classes.edn")

(def ^:private react-evidence
  (delay
    (if-let [url (io/resource fixture-resource)]
      (edn/read-string (slurp url))
      (throw (ex-info (str "the react-dom evidence fixture is not on the test "
                           "classpath — without it every assertion below "
                           "iterates nothing and passes vacuously")
                      {:resource fixture-resource})))))

(defn- rows [] (:rows @react-evidence))

(defn- collapse
  "The roster's key shape: hyphens removed, lower-cased."
  [attribute-name]
  (str/lower-case (str/replace attribute-name "-" "")))

;; ---------------------------------------------------------------------------
;; Deriving React's class from React's bytes.
;;
;; Case-insensitive because `pushBooleanAttribute` lower-cases three names on
;; the way out (`autoFocus` -> `autofocus=""`); anchored on the leading space
;; react-dom writes before every attribute so a short name cannot match inside
;; a tag name or another attribute's value.
;; ---------------------------------------------------------------------------

(defn- react-writes? [attribute-name markup suffix]
  (str/includes? (str/lower-case markup)
                 (str " " (str/lower-case attribute-name) suffix)))

(defn- react-class
  "One evidence row -> the class react-dom applied: `:stringify` (both
  booleans reach markup as `=\"true\"` / `=\"false\"`), `:presence` (`true`
  reaches markup, `false` does not), or `:ordinary` (neither does)."
  [{:keys [attribute true-markup false-markup]}]
  (let [mentions? #(react-writes? attribute % "=\"")]
    (cond
      (and (react-writes? attribute true-markup "=\"true\"")
           (react-writes? attribute false-markup "=\"false\""))
      :stringify

      (and (react-writes? attribute true-markup "=\"\"")
           (not (mentions? false-markup)))
      :presence

      (and (not (mentions? true-markup)) (not (mentions? false-markup)))
      :ordinary

      :else
      (throw (ex-info "react-dom markup this test cannot classify"
                      {:attribute attribute
                       :true-markup true-markup
                       :false-markup false-markup})))))

;; ---------------------------------------------------------------------------
;; The two documented divergences.
;;
;; Both are DECISIONS, recorded here so a later reader meets the reasoning
;; rather than a mystery, and pinned so that the premise changing is a
;; failure rather than a silent drift.
;; ---------------------------------------------------------------------------

(def ^:private divergences
  {"value"
   {:react       :stringify
    :re-frame    :ordinary
    :because
    "react-dom stringifies a boolean `value` because `value` shares a code
     branch with the booleanish names, not because it is one — that branch is
     the generic \"push whatever you were given\" path, and a string or number
     `value` (the only kinds a form control has) serialises identically under
     our `:ordinary` arm. The classification only bites for a BOOLEAN `value`,
     which on a form control is an author error rather than a state. And
     `value` is a 004B form-control special form whose meaning already differs
     per element (an attribute on `<input>`, the text child of `<textarea>`,
     `selected` on an `<option>` for `<select>`); putting it in this shared
     roster would change `ui-tree`'s handling of that special form from here,
     which is 004B's call to make, not this artefact's."}

   "ismap"
   {:react       :none      ; react-dom refuses a boolean `ismap` outright
    :re-frame    :presence
    :because
    "004B §Booleans and their neighbours names `ismap` in the boolean set,
     and the roster follows the spec. The spec's ORIGINAL justification for
     the name was measured false (rf2-u6zw): it read \"the react-dom/server
     19.2.0 boolean-attribute list ... includes `ismap` (React 19 dropped the
     camel `isMap` prop)\", but react-dom 19.2.0 accepts no boolean `ismap` in
     ANY spelling — the name is absent from its `possibleStandardNames`
     altogether, a boolean warns \"Received `true` for a non-boolean
     attribute\" and emits NOTHING, and so it can never reach this evidence
     fixture. 004B has since RULED on the row rather than merely naming it:
     `ismap` IS a real HTML boolean attribute on `<img>`, presence is the
     HTML-correct rendering, and the grammar tracks HTML where the two part
     on a genuine HTML boolean attribute. The expected class below is
     therefore unchanged — what changed is that the divergence is now stated
     in 004B with its reason instead of hiding inside a false provenance."}})

(defn- expected-class
  "What `boolean-attr-class` must say for `attribute-name`: React's class,
  unless this is one of the documented divergences."
  [attribute-name react-verdict]
  (get-in divergences [attribute-name :re-frame] react-verdict))

;; ---------------------------------------------------------------------------
;; 1. The evidence itself is real.
;; ---------------------------------------------------------------------------

(deftest react-evidence-fixture-is-present-and-substantial
  (testing "rf2-r9kf — the fixture loads, names the react-dom it was measured
            against, and carries a plausible number of rows. A missing or
            empty fixture would make every doseq below iterate nothing and
            report a clean pass, which is the one failure mode this whole
            file exists to rule out"
    (is (string? (:react-dom-version @react-evidence))
        "the fixture records which react-dom produced it")
    (is (<= 30 (count (rows)))
        "react-dom 19 carries three dozen boolean-class attributes")
    (is (every? (fn [{:keys [attribute true-markup false-markup]}]
                  (and (string? attribute)
                       (string? true-markup)
                       (string? false-markup)))
                (rows))
        "every row carries an attribute name and both markup strings"))

  (testing "rf2-r9kf — NON-VACUITY: the eight names the audit found missing
            are actually IN the evidence, so the agreement asserted below is
            agreement about them and not about a fixture that omits them"
    (let [named (set (map :attribute (rows)))]
      (doseq [attribute ["disablePictureInPicture" "disableRemotePlayback"
                         "scoped" "seamless"
                         "autoReverse" "externalResourcesRequired"
                         "focusable" "preserveAlpha"]]
        (is (contains? named attribute)
            (str attribute " must be in the react-dom evidence"))))))

;; ---------------------------------------------------------------------------
;; 2. The classifier agrees with React — in both directions.
;; ---------------------------------------------------------------------------

(deftest boolean-attr-class-agrees-with-installed-react-dom
  (testing "rf2-r9kf — every attribute react-dom accepts a boolean for is
            classified the way react-dom classifies it. This is the check the
            two-serialiser parity test structurally cannot make: the evidence
            comes from outside both consumers of the roster"
    (doseq [row (rows)]
      (let [attribute (:attribute row)
            react     (react-class row)]
        (is (= (expected-class attribute react)
               (rf.ssr.html-helpers/boolean-attr-class attribute))
            (str attribute " — react-dom " (:react-dom-version @react-evidence)
                 " renders " (pr-str (:true-markup row)) " / "
                 (pr-str (:false-markup row))))))))

(deftest documented-divergences-still-have-their-premise
  (testing "rf2-r9kf — `value` is deliberately NOT booleanish here. The
            exception is only defensible while react-dom really does
            stringify it, so the premise is pinned: if react-dom stops, this
            reds and the decision gets re-taken rather than inherited"
    (let [row (first (filter #(= "value" (:attribute %)) (rows)))]
      (is (some? row) "react-dom's evidence still carries a `value` row")
      (is (= :stringify (react-class row))
          "react-dom stringifies a boolean `value`")
      (is (= :ordinary (rf.ssr.html-helpers/boolean-attr-class "value"))
          "re-frame leaves `value` ordinary — see `divergences`")))

  (testing "rf2-r9kf — `ismap` is the divergence in the OTHER direction: the
            roster carries it on 004B's word, react-dom refuses a boolean
            `ismap` and so cannot appear in the evidence at all"
    (is (not (contains? (set (map (comp collapse :attribute) (rows))) "ismap"))
        "react-dom accepts no boolean `ismap`, so no row can exist for it")
    (is (= :presence (rf.ssr.html-helpers/boolean-attr-class "ismap"))
        "the roster follows 004B here; since rf2-u6zw the divergence is ruled
         and stated in 004B's own row, not merely recorded downstream")))

(deftest every-roster-name-is-backed-by-react-evidence
  (testing "rf2-r9kf — the REVERSE direction. Agreeing with React about the
            names React named is half a check: a name invented here, or one
            react-dom has since dropped, would never appear in the evidence
            and would sail through the test above. Every roster member must be
            evidenced, or be a documented divergence"
    (let [evidenced (into {} (map (juxt (comp collapse :attribute) react-class))
                          (rows))
          excused   (set (map collapse (keys divergences)))]
      (doseq [[roster-name roster] [["boolean-attrs" rf.ssr.html-helpers/boolean-attrs]
                                    ["booleanish-attrs" rf.ssr.html-helpers/booleanish-attrs]
                                    ["overloaded-boolean-attrs"
                                     rf.ssr.html-helpers/overloaded-boolean-attrs]]
              attribute roster]
        (when-not (contains? excused attribute)
          (is (contains? evidenced attribute)
              (str roster-name " carries " (pr-str attribute)
                   ", which react-dom "
                   (:react-dom-version @react-evidence)
                   " accepts no boolean for")))))))

;; ---------------------------------------------------------------------------
;; 3. The public emitters follow the roster — every row, both values.
;;
;; The class is compared rather than the bytes for the structural-tree
;; serialiser, whose presence spelling (`disabled=""`) and React prop-name
;; mapping differ from the hiccup emitter's by design (004B: one table, two
;; pipelines). The hiccup paths write the author's name verbatim, so those
;; two are asserted as exact strings.
;; ---------------------------------------------------------------------------

(defn- expected-hiccup-markup
  "The `<div>` markup the hiccup emitters must produce for `attribute` set to
  `value`, given the class."
  [klass attribute value]
  (case klass
    :stringify (str "<div " attribute "=\"" value "\"></div>")
    :presence  (if value (str "<div " attribute "></div>") "<div></div>")
    :ordinary  "<div></div>"))

(deftest render-to-string-follows-react-for-every-evidenced-attribute
  (testing "rf2-r9kf — the PUBLIC hiccup render path, table-driven over the
            whole react-dom evidence and both boolean values. A presence name
            emits a bare attribute for `true` and nothing for `false`; a
            stringifying name emits a quoted `\"true\"`/`\"false\"` and is
            NEVER omitted; an ordinary name never becomes a bare attribute"
    (doseq [row   (rows)
            value [true false]]
      (let [attribute (:attribute row)
            klass     (expected-class attribute (react-class row))]
        (is (= (expected-hiccup-markup klass attribute value)
               (rf.ssr.emit/render-to-string [:div {(keyword attribute) value}] {}))
            (str attribute " " value " (" klass ")"))))))

(deftest render-shell-follows-react-for-every-evidenced-attribute
  (testing "rf2-r9kf — the STREAMING hiccup mode re-derives attributes through
            the same shared helper, so the same table must hold there. A fix
            landing on one hiccup mode only is exactly the drift this pins"
    (doseq [row   (rows)
            value [true false]]
      (let [attribute (:attribute row)
            klass     (expected-class attribute (react-class row))]
        (is (= (expected-hiccup-markup klass attribute value)
               (:shell-html
                (rf.ssr.streaming/render-shell [:div {(keyword attribute) value}])))
            (str attribute " " value " (" klass ")"))))))

(defn- observed-class
  "Which class a serialiser applied, read off its own output and compared
  against its no-attribute baseline. Name-agnostic on purpose: the
  structural-tree serialiser renames attributes through the React prop
  vocabulary, so matching on the author's name would misread a rename as an
  omission."
  [baseline true-html false-html]
  (cond
    (and (str/includes? true-html "=\"true\"")
         (str/includes? false-html "=\"false\""))
    :stringify

    (and (not= baseline true-html) (= baseline false-html))
    :presence

    (and (= baseline true-html) (= baseline false-html))
    :ordinary

    :else
    (throw (ex-info "serialiser output this test cannot classify"
                    {:baseline baseline :true-html true-html
                     :false-html false-html}))))

(defn- tree-html [attrs]
  (rf.ssr.ui-tree/emit-ui-tree {:rf.ui/tree-version 1 :tag :div :attrs attrs}))

(deftest structural-tree-serialiser-follows-react-for-every-evidenced-attribute
  (testing "rf2-r9kf AC5 — the structural-tree serialiser is the parity
            REFERENCE, and it now has to agree with react-dom too rather than
            merely with the hiccup emitter. Compared as classes, not bytes:
            the two pipelines stay separate (004B) and differ in presence
            spelling and attribute naming; what must not differ is the class"
    (let [baseline (tree-html {})]
      (doseq [row (rows)]
        (let [attribute (:attribute row)
              klass     (expected-class attribute (react-class row))
              key       (keyword attribute)]
          (is (= klass
                 (observed-class baseline
                                 (tree-html {key true})
                                 (tree-html {key false})))
              (str attribute " (" klass ") — structural-tree serialiser")))))))
