(ns re-frame.machines.mermaid-public-smoke-test
  "Public-surface smoke per rf2-yamkm — exercises `re-frame.machines.mermaid/emit`
  from an arms-length consumer namespace (no internal-ns access).

  The deeper coverage of edge cases (compound nesting, parallel
  regions, validation, sanitisation, …) lives in
  `re-frame.machines.mermaid-cljs-test`. This namespace is the
  consumer-side seam: a downstream caller should be able to require
  the public ns alone and get a Mermaid string back without needing
  to know anything about the emitter's internals."
  (:require [clojure.test :refer [deftest is testing]]
            [clojure.string :as str]
            [re-frame.machines.mermaid :as mermaid]))

(deftest public-emit-from-outside-the-ns
  (testing "the public `emit` fn is reachable from an arms-length consumer"
    (let [definition {:initial :idle
                      :states  {:idle    {:on {:start :loading}}
                                :loading {:on {:done :idle}}}}
          out        (mermaid/emit definition)]
      (is (string? out))
      (is (str/includes? out "stateDiagram-v2"))
      (is (str/includes? out "[*] --> idle"))
      (is (str/includes? out "idle --> loading : start"))
      (is (str/includes? out "loading --> idle : done"))
      ;; Default fence + header are on per the public contract
      (is (str/starts-with? out "```mermaid"))
      (is (str/ends-with?   out "```"))
      (is (str/includes?    out "%% Generated by re-frame.machines.mermaid")))))

(deftest public-emit-honours-option-map
  (testing "options propagate through the public surface"
    (let [definition {:initial :on
                      :states  {:on  {:on {:toggle :off}}
                                :off {:on {:toggle :on}}}}
          plain      (mermaid/emit definition {:fenced?         false
                                               :header-comment? false})]
      (is (not (str/includes? plain "```")))
      (is (not (str/includes? plain "%%")))
      (is (str/includes? plain "stateDiagram-v2")))))
