(ns reagent2.dom.boolean-attr-react-parity-cljs-test
  "rf2-4hjw — the EXTERNAL anchor for `reagent2.dom.server`'s boolean
  attribute-value rosters.

  WHY THIS EXISTS, AND WHY IT IS NOT `parity_cljs_test.cljs`.
  `parity_cljs_test` renders a corpus of representative hiccup both
  ways and diffs byte-for-byte against `react-dom/server`, which is
  the right SHAPE of check — the reference really is outside this
  artefact. But its candidate set is a hand-written corpus, so it can
  only catch what the corpus happens to contain, and the corpus
  contained exactly two boolean rows (`{:disabled true}` and
  `{:disabled false}`). Six react-dom presence names were missing
  from the roster and the whole stringifying class was absent, and
  every assertion in the file stayed green.

  That is the same structural blind spot the rf2-r9kf SSR audit found
  wearing a different disguise. There, two serialisers sharing one
  roster made their parity test agree on the same wrong answer; here,
  a genuine external reference is asked only the questions the corpus
  thought to ask. A parity test can only validate what something
  OUTSIDE the thing under test SUPPLIES — and supplying the questions
  is half of that.

  So the candidate NAMES come from react-dom too:

    1. Candidates are the values of react-dom's own
       `possibleStandardNames` table, scraped out of the development
       build — every canonical DOM prop name React knows. A candidate
       list derived from our own roster would reproduce the blind spot
       verbatim: a name missing from the roster would be missing from
       the probe.
    2. A candidate is a BOOLEAN-CLASS attribute iff React's
       development build renders `{name: true}` WITHOUT its
       \"Received `true` for a non-boolean attribute\" warning. That is
       React's own statement of which attributes take booleans, and it
       is what bounds this to a roster check rather than a react-dom
       clone: the numeric attributes (`cols`, `rows`, `size`, `span`,
       `rowSpan`, `start`) coerce a boolean into markup through
       arithmetic, they warn, and they are excluded on React's verdict
       rather than ours.
    3. The CLASS is derived from React's markup bytes, on the first
       probe element where the attribute reaches markup at all
       (`checked` needs an `<input>`, `selected` an `<option>`).

  MEASURED LIVE, NOT FROM A FIXTURE. The SSR probe writes react-dom's
  bytes to a committed `.edn` because its consumer is a JVM suite that
  must not need `node_modules`; that fixture is regenerated by hand,
  so a react-dom bump does not automatically red. This test runs under
  `:node-test` with react-dom already resolvable, so it re-derives
  everything at run time and takes the better half of that trade: a
  react-dom bump that moves a name into, out of, or between classes
  reds this gate on the next `npm run test:cljs` with no regeneration
  step and nothing to forget.

  BOTH DIRECTIONS, over react-dom's whole candidate space:

    - a name React classifies that the serializer does not → red
      (`boolean-classes-agree-with-installed-react-dom`);
    - a name the serializer treats as boolean-class that React does
      NOT accept a boolean for → red
      (`non-boolean-react-attributes-carry-no-boolean-class`).

  The serializer's class is read from its EMITTED MARKUP through the
  public `render-to-static-markup`, never from the rosters (which are
  private, and reading them would make the check vacuous).

  WHAT THIS PROBE DOES NOT BOUND: a hypothetical roster entry that is
  not one of react-dom's `possibleStandardNames` values would escape
  the reverse arm, because the candidate space is React's. Every
  current entry is in that space.

  TWO ALLOW-LISTED DIVERGENCES, each with its reason, applied by
  `classify` below rather than by a global diff filter:

    1. PRESENCE SHORT FORM. React writes `disabled=\"\"`; this
       serializer writes the equivalent HTML5 short form `disabled`.
       Pre-existing and allow-listed by IMPL-SPEC §8.7.
    2. PRESENCE NAME CASE. React preserves camelCase for most
       presence names (`readOnly=\"\"`, `noModule=\"\"`) while
       lowercasing three of them (`autoFocus` → `autofocus`); this
       serializer lowercases all of them. HTML attribute names are
       ASCII case-insensitive, every presence-class member is an HTML
       (not SVG) attribute, and the lowercase key is what lets
       `:read-only`, `:readOnly` and `:readonly` all classify. The
       STRINGIFYING class is compared case-SENSITIVELY, because four
       of its members (`autoReverse`, `externalResourcesRequired`,
       `focusable`, `preserveAlpha`) are case-sensitive SVG
       attributes where lowercasing would be wrong."
  (:require [cljs.test :refer-macros [deftest is testing]]
            [clojure.string :as str]
            [reagent2.dom.server :as server]
            ["react" :as react]))

;; ---------------------------------------------------------------------------
;; Node seam
;;
;; `js/require` for node built-ins is established in this repo's
;; :node-test suites (re-frame.hicasso.examples.fence-cljs-test,
;; re-frame.test-quiet.shadow-node). react-dom's root is found by
;; walking up from the compiled test's directory rather than through
;; `require.resolve`, so the probe does not depend on how the build
;; tool shapes `require`.
;; ---------------------------------------------------------------------------

(def ^:private node-fs (js/require "fs"))
(def ^:private node-path (js/require "path"))

(defn- react-dom-root
  "Absolute path of the installed react-dom package."
  []
  (loop [dir js/__dirname
         hops 0]
    (let [candidate (.join node-path dir "node_modules" "react-dom" "package.json")]
      (cond
        (.existsSync node-fs candidate)
        (.dirname node-path candidate)

        (> hops 12)
        (throw (js/Error.
                (str "no node_modules/react-dom found walking up from "
                     js/__dirname " — this probe needs the installed package, "
                     "and an empty candidate set would read as a clean pass.")))

        :else
        (recur (.dirname node-path dir) (inc hops))))))

(def ^:private react-dom-dir (react-dom-root))

(def ^:private react-dom-version
  (-> (.readFileSync node-fs (.join node-path react-dom-dir "package.json") "utf8")
      (js/JSON.parse)
      (.-version)))

;; The LEGACY node builds, because they are the pair exporting
;; `renderToStaticMarkup` — the one-shot string API this probe needs.
;; They carry the same `pushAttribute` code as the streaming builds, so
;; the verdicts are react-dom's and not a legacy dialect's.
(def ^:private dev-server-path
  (.join node-path react-dom-dir "cjs" "react-dom-server-legacy.node.development.js"))

(def ^:private prod-server-path
  (.join node-path react-dom-dir "cjs" "react-dom-server-legacy.node.production.js"))

(def ^:private dev-server (js/require dev-server-path))
(def ^:private prod-server (js/require prod-server-path))

;; ---------------------------------------------------------------------------
;; 1. Candidate names — react-dom's own `possibleStandardNames`.
;; ---------------------------------------------------------------------------

(defn- scrape-possible-standard-names
  "Every value of react-dom's `possibleStandardNames` object literal,
  read out of the development build's source text. Balanced-brace scan
  rather than a regex, because the literal spans hundreds of lines."
  [source]
  (let [marker "possibleStandardNames = {"
        start  (str/index-of source marker)
        _      (when-not start
                 (throw (js/Error.
                         (str "react-dom " react-dom-version " carries no "
                              "`possibleStandardNames = {` — the scrape anchor "
                              "moved; fix this probe rather than accepting an "
                              "empty candidate set."))))
        open   (+ start (dec (count marker)))
        end    (loop [i open depth 0]
                 (cond
                   (>= i (count source))
                   (throw (js/Error. "unbalanced `possibleStandardNames` literal"))

                   (= "{" (subs source i (inc i))) (recur (inc i) (inc depth))

                   (= "}" (subs source i (inc i)))
                   (if (= 1 depth) (inc i) (recur (inc i) (dec depth)))

                   :else (recur (inc i) depth)))
        table  (js/JSON.parse
                (-> (subs source open end)
                    ;; A flat object literal of unquoted-or-quoted string
                    ;; keys to string values. Quote the bare keys so
                    ;; JSON.parse can read it without `eval`.
                    (str/replace #"([{,])\s*([A-Za-z_$][\w$-]*)\s*:" "$1\"$2\":")
                    (str/replace #",\s*\}" "}")))]
    (vec (distinct (vals (js->clj table))))))

(def ^:private candidates
  (let [names (scrape-possible-standard-names
               (.readFileSync node-fs dev-server-path "utf8"))]
    ;; `aria-*` / `data-*` are a PREFIX rule in react-dom's default
    ;; branch rather than named entries, so they cannot come out of the
    ;; table. Two representatives each keep the prefix rule pinned.
    (into names ["aria-expanded" "aria-hidden" "data-open" "data-collapsed"])))

;; ---------------------------------------------------------------------------
;; 2. Boolean-class filter — React's own dev warning is the verdict.
;; ---------------------------------------------------------------------------

(def ^:private non-boolean-warning "for a non-boolean attribute")

(defn- react-accepts-boolean?
  "True iff React's DEVELOPMENT build renders `{name true}` without its
  \"Received `true` for a non-boolean attribute\" warning."
  [attr-name]
  (let [original-error js/console.error
        original-warn  js/console.warn
        warned         (atom false)
        watch          (fn [& args]
                         (let [first-arg (first args)]
                           (when (and (string? first-arg)
                                      (str/includes? first-arg non-boolean-warning))
                             (reset! warned true))))]
    (set! js/console.error watch)
    (set! js/console.warn watch)
    (try
      (.renderToStaticMarkup dev-server
                             (react/createElement "div" (js-obj attr-name true)))
      (catch :default _
        ;; A prop React refuses outright is not a boolean-class attribute.
        (reset! warned true))
      (finally
        (set! js/console.error original-error)
        (set! js/console.warn original-warn)))
    (not @warned)))

;; ---------------------------------------------------------------------------
;; 3. Markup, and the class derived from it.
;; ---------------------------------------------------------------------------

(def ^:private probe-elements ["div" "input" "option" "select" "video"])

(defn- react-markup
  [element attr-name value]
  (try
    (.renderToStaticMarkup prod-server
                           (react/createElement element (js-obj attr-name value)))
    (catch :default _ nil)))

(defn- slim-markup
  [element attr-name value]
  (server/render-to-static-markup
   [(keyword element) {(keyword attr-name) value}]))

(defn- mentions?
  "Does `markup` carry ` <attr-name><suffix>`? Anchored on the leading
  space every attribute is written after, so a short name cannot match
  inside a tag name or another attribute's value."
  [markup attr-name suffix case-sensitive?]
  (boolean
   (and markup
        (if case-sensitive?
          (str/includes? markup (str " " attr-name suffix))
          (str/includes? (str/lower-case markup)
                         (str/lower-case (str " " attr-name suffix)))))))

(defn- classify
  "Derive the boolean class from a serialiser's own bytes.

  `presence` accepts BOTH spellings of the empty-value form — React's
  `name=\"\"` and the HTML5 short form `name` this serializer emits —
  which is allow-listed divergence 1. Case-sensitivity is the caller's
  choice: divergence 2 makes presence-class names case-insensitive."
  [attr-name true-markup false-markup case-sensitive?]
  (let [has?     (fn [markup suffix] (mentions? markup attr-name suffix case-sensitive?))
        valued?  (fn [markup] (has? markup "=\""))
        ;; Short form: the name is followed by a space or the tag close.
        short?   (fn [markup]
                   (or (has? markup ">") (has? markup " ") (has? markup "/")))]
    (cond
      (and (has? true-markup "=\"true\"") (has? false-markup "=\"false\""))
      :stringify

      (and (or (has? true-markup "=\"\"") (and (short? true-markup)
                                               (not (valued? true-markup))))
           (not (valued? false-markup))
           (not (short? false-markup)))
      :presence

      (and (not (valued? true-markup)) (not (short? true-markup))
           (not (valued? false-markup)) (not (short? false-markup)))
      :dropped

      :else
      :unclassifiable)))

(defn- react-class
  "React's class for `attr-name`, plus the element it was measured on.
  Returns `nil` when no probe element shows the attribute at all — the
  caller reads that as `:dropped` on a `<div>`.

  Derived CASE-INSENSITIVELY, because react-dom lowercases a handful of
  names on the way out (`autoFocus` → `autofocus=\"\"`) and a
  case-sensitive read of React's own bytes calls those absent — a wrong
  class that still looks like a measurement. Measured: this test read
  `autoFocus` as `:dropped` until the flag was flipped, and then failed
  the reverse arm for emitting markup React supposedly never writes."
  [attr-name]
  (reduce
   (fn [_ element]
     (let [t (react-markup element attr-name true)
           f (react-markup element attr-name false)]
       (if (or (nil? t) (nil? f))
         nil
         (let [k (classify attr-name t f false)]
           (if (contains? #{:presence :stringify} k)
             (reduced {:element element :class k :true-markup t :false-markup f})
             nil)))))
   nil
   probe-elements))

;; ---------------------------------------------------------------------------
;; The React-derived evidence, measured once.
;; ---------------------------------------------------------------------------

(def ^:private evidence
  "One row per react-dom candidate name: React's boolean verdict, and
  where React classifies a boolean, the class and the element it shows
  on."
  (mapv (fn [attr-name]
          (let [boolean-attr? (react-accepts-boolean? attr-name)
                measured      (when boolean-attr? (react-class attr-name))]
            {:attribute attr-name
             :react-boolean? boolean-attr?
             :element   (or (:element measured) "div")
             :class     (if measured (:class measured) :dropped)}))
        candidates))

(def ^:private boolean-class-rows
  (filterv (fn [row] (and (:react-boolean? row) (= :stringify (:class row))))
           evidence))

(def ^:private presence-rows
  (filterv (fn [row] (and (:react-boolean? row) (= :presence (:class row))))
           evidence))

;; ---------------------------------------------------------------------------
;; Guards on the evidence itself.
;;
;; An empty or badly shrunken candidate set is the failure mode that
;; reads as a clean measurement: every table-driven assertion below
;; would iterate nothing and pass.
;; ---------------------------------------------------------------------------

(deftest react-evidence-is-plausible
  (testing "the probe actually measured the installed react-dom"
    (is (str/starts-with? react-dom-version "19.")
        (str "react-dom " react-dom-version
             " — this probe was written against the 19.x builds"))
    (is (> (count candidates) 300)
        (str "only " (count candidates) " candidate names scraped from "
             "possibleStandardNames — the scrape is broken, and an empty "
             "candidate set would read as a clean pass"))
    (is (> (count presence-rows) 20)
        (str "only " (count presence-rows) " presence-class names measured"))
    (is (> (count boolean-class-rows) 5)
        (str "only " (count boolean-class-rows) " stringifying-class names "
             "measured"))
    (is (>= (+ (count presence-rows) (count boolean-class-rows)) 30)
        "react-dom 19 carries three dozen boolean-class names")))

;; ---------------------------------------------------------------------------
;; Direction 1 — every name React classifies, the serializer classifies
;; the same way.
;; ---------------------------------------------------------------------------

(deftest boolean-classes-agree-with-installed-react-dom
  (testing "react-dom's boolean classes, derived from react-dom's own bytes"
    (doseq [{:keys [attribute element class]} (concat presence-rows boolean-class-rows)]
      (let [;; Divergence 2: presence-class names compare
            ;; case-insensitively, stringifying names byte-exact.
            case-sensitive? (= :stringify class)
            t (slim-markup element attribute true)
            f (slim-markup element attribute false)]
        (is (= class (classify attribute t f case-sensitive?))
            (str "react-dom " react-dom-version " classifies `" attribute
                 "` as " class " on <" element ">; render-to-static-markup "
                 "emitted " (pr-str t) " / " (pr-str f)))))))

;; ---------------------------------------------------------------------------
;; Direction 2 — the serializer carries no boolean class React does not.
;; ---------------------------------------------------------------------------

(deftest non-boolean-react-attributes-carry-no-boolean-class
  (testing "a name React puts no boolean into markup for emits nothing either"
    ;; Both halves of "not a boolean class": the names React WARNS about
    ;; (`cols`, `size`, `href`, …) and the names it accepts a boolean for
    ;; yet never writes (`defaultChecked`, `children`, `is`, …).
    (doseq [{:keys [attribute]}
            (remove (fn [row] (contains? #{:presence :stringify} (:class row)))
                    evidence)]
      (let [t (slim-markup "div" attribute true)
            f (slim-markup "div" attribute false)]
        (is (= :dropped (classify attribute t f false))
            (str "react-dom " react-dom-version " puts no boolean into markup "
                 "for `" attribute "` — it either warns the name is not a "
                 "boolean attribute, or accepts one and writes nothing — so a "
                 "boolean value must not reach markup here either; "
                 "render-to-static-markup emitted " (pr-str t) " / " (pr-str f)))))))

;; ---------------------------------------------------------------------------
;; The OVERLOADED class, which boolean probing cannot see.
;;
;; `download` and `capture` are indistinguishable from the presence
;; class while only booleans are supplied — both emit the bare name on
;; true and nothing on false. The distinction is a NON-boolean value,
;; which the probe above deliberately does not supply, so it is pinned
;; here against live react-dom with a third value. (This is the gap the
;; SSR probe recorded and could not close: its fixture is boolean-only.)
;; ---------------------------------------------------------------------------

(deftest overloaded-booleans-keep-a-non-boolean-value
  (doseq [[element attribute value]
          [["a" "download" "report.pdf"]
           ["input" "capture" "user"]]]
    (testing (str "`" attribute "` is overloaded, not presence")
      (let [react-html (react-markup element attribute value)
            slim-html  (slim-markup element attribute value)]
        (is (str/includes? react-html (str " " attribute "=\"" value "\""))
            (str "control: react-dom " react-dom-version
                 " must keep the non-boolean value — got " (pr-str react-html)))
        (is (str/includes? slim-html (str " " attribute "=\"" value "\""))
            (str "a presence-class collapse would throw the value away — got "
                 (pr-str slim-html)))))))

;; ---------------------------------------------------------------------------
;; Explicit pins.
;;
;; The table-driven checks above are the gate; these state the intent in
;; bytes, so it stays readable without running react-dom and so the six
;; names rf2-4hjw named are each visibly exercised.
;; ---------------------------------------------------------------------------

(deftest presence-names-added-by-rf2-4hjw
  (testing "each of the six emits the HTML5 short form on true, nothing on false"
    (doseq [[k emitted] [[:inert "inert"]
                         [:noModule "nomodule"]
                         [:scoped "scoped"]
                         [:seamless "seamless"]
                         [:disablePictureInPicture "disablepictureinpicture"]
                         [:disableRemotePlayback "disableremoteplayback"]]]
      (is (= (str "<div " emitted "></div>")
             (server/render-to-static-markup [:div {k true}])))
      (is (= "<div></div>"
             (server/render-to-static-markup [:div {k false}]))))))

(deftest stringifying-names-emit-true-and-false
  (testing "the booleanish family stringifies BOTH values"
    (doseq [[k emitted] [[:contentEditable "contentEditable"]
                         [:draggable "draggable"]
                         [:spellCheck "spellCheck"]
                         [:autoReverse "autoReverse"]
                         [:externalResourcesRequired "externalResourcesRequired"]
                         [:focusable "focusable"]
                         [:preserveAlpha "preserveAlpha"]]]
      (is (= (str "<div " emitted "=\"true\"></div>")
             (server/render-to-static-markup [:div {k true}])))
      (is (= (str "<div " emitted "=\"false\"></div>")
             (server/render-to-static-markup [:div {k false}])))))
  (testing "the case-sensitive SVG members are NOT lowercased"
    (is (= "<feComposite preserveAlpha=\"true\"></feComposite>"
           (server/render-to-static-markup [:feComposite {:preserve-alpha true}])))))

(deftest aria-and-data-booleans-stringify
  (testing "rf2-r9kf's headline case, in this artefact: a false that carries meaning"
    (is (= "<button aria-expanded=\"true\">x</button>"
           (server/render-to-static-markup [:button {:aria-expanded true} "x"])))
    (is (= "<button aria-expanded=\"false\">x</button>"
           (server/render-to-static-markup [:button {:aria-expanded false} "x"])))
    (is (= "<div data-collapsed=\"false\"></div>"
           (server/render-to-static-markup [:div {:data-collapsed false}])))))

(deftest nested-editable-parent-keeps-the-child-opt-out
  (testing "an explicit contentEditable=false child must not inherit editability"
    (is (= (str "<div contentEditable=\"true\">"
                "<section contentEditable=\"false\">locked</section>"
                "</div>")
           (server/render-to-static-markup
            [:div {:content-editable true}
             [:section {:content-editable false} "locked"]])))))

(deftest overloaded-booleans-pinned
  (testing "download/capture: true → short form, false → omitted, value → kept"
    (is (= "<a download></a>" (server/render-to-static-markup [:a {:download true}])))
    (is (= "<a></a>" (server/render-to-static-markup [:a {:download false}])))
    (is (= "<a download=\"report.pdf\"></a>"
           (server/render-to-static-markup [:a {:download "report.pdf"}])))
    (is (= "<input capture>" (server/render-to-static-markup [:input {:capture true}])))
    (is (= "<input capture=\"user\">"
           (server/render-to-static-markup [:input {:capture "user"}])))))

(deftest controls-that-must-not-move
  (testing "the presence class keeps presence semantics"
    (is (= "<input disabled>" (server/render-to-static-markup [:input {:disabled true}])))
    (is (= "<input>" (server/render-to-static-markup [:input {:disabled false}])))
    (is (= "<input readonly>"
           (server/render-to-static-markup [:input {:read-only true}]))
        "the lowercase roster key is what makes :read-only classify"))
  (testing "a truthy non-boolean on a presence name collapses, as react-dom does"
    (is (= "<div hidden></div>" (server/render-to-static-markup [:div {:hidden "until-found"}]))))
  (testing "a boolean on an ordinary attribute does not become a bare attribute"
    (is (= "<div></div>" (server/render-to-static-markup [:div {:title true}])))
    (is (= "<div></div>" (server/render-to-static-markup [:div {:title false}]))))
  (testing "React-internal props stay dropped whatever their value"
    (is (= "<div></div>" (server/render-to-static-markup [:div {:key false}])))
    (is (= "<div></div>" (server/render-to-static-markup [:div {:suppressHydrationWarning true}])))))
