(ns scaffold-smoke-test
  "CI teeth for examples/ui/minimal-counter — the minimal runnable re-frame.ui
   scaffold (rf2-vxgfnd.281).

   Two tiers:

     STRUCTURAL (always) — read the file manifest straight out of the
     scaffold's README, and assert it matches what is on disk: every listed
     file present, no un-listed source/config file hiding alongside them, the
     two load-bearing shadow-cljs settings present, the host page wired, and
     deps.edn's :local/root coords resolving. Pure file reads; no Node.

     COMPILE (env RF2_UI_SCAFFOLD_COMPILE=1) — the real proof. Materialize
     ONLY the manifest files into a temp dir, `npm install`, and
     `npx shadow-cljs compile app`. Then the omission matrix: for each manifest
     file, materialize the manifest MINUS that file and assert the result is no
     longer viable. That is what makes every listed file genuinely load-bearing
     rather than merely present — a gate that would pass on a broken scaffold is
     worthless. Needs Node + a monorepo checkout (deps.edn resolves the
     framework via :local/root); the CI job sets the flag.

   The manifest is the single source of truth: it lives in the README (the
   file authors read) and is parsed here (the file CI runs), so the documented
   claim and the tested contract cannot drift."
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.string :as str]
            [clojure.test :refer [deftest is testing]]))

;; ---------------------------------------------------------------------------
;; Locating the scaffold
;; ---------------------------------------------------------------------------

(def ^:private scaffold-rel "examples/ui/minimal-counter")

(defn- repo-root
  "Walk up from the working dir until the scaffold is found."
  []
  (or (some (fn [dir]
              (let [d (.getCanonicalFile (io/file dir))]
                (when (.isFile (io/file d scaffold-rel "README.md")) d)))
            (take 8 (iterate #(io/file % "..") (io/file "."))))
      (throw (ex-info "Could not locate examples/ui/minimal-counter from the working dir"
                      {:cwd (System/getProperty "user.dir")}))))

(def ^:private root (delay (repo-root)))

(defn- scaffold-dir [] (io/file @root scaffold-rel))

(defn- scaffold-file [rel] (io/file (scaffold-dir) rel))

;; ---------------------------------------------------------------------------
;; The manifest — parsed from the README, not hardcoded here
;; ---------------------------------------------------------------------------

(defn- manifest
  "The load-bearing file list, read from the README's rf2:scaffold-manifest
   fenced block. Every path is relative to the scaffold dir."
  []
  (let [readme (slurp (scaffold-file "README.md"))
        block  (second (re-find #"(?s)rf2:scaffold-manifest.*?```text\r?\n(.*?)```"
                                readme))]
    (when-not block
      (throw (ex-info "README has no rf2:scaffold-manifest ```text block" {})))
    (->> (str/split-lines block)
         (map str/trim)
         (remove str/blank?)
         vec)))

;; ---------------------------------------------------------------------------
;; STRUCTURAL tier
;; ---------------------------------------------------------------------------

(deftest manifest-is-nonempty-and-on-disk
  (let [files (manifest)]
    (is (seq files) "the README manifest parsed to zero files")
    (doseq [rel files]
      (is (.isFile (scaffold-file rel))
          (str "manifest lists " rel " but it is not a file in the scaffold")))))

(deftest no-unlisted-source-or-config-file
  (testing "nothing load-bearing hides outside the documented manifest"
    ;; Walk the scaffold tree, ignoring generated output and repo-hygiene
    ;; files. Whatever remains must be exactly the manifest — so a future edit
    ;; that adds a genuinely-needed file without listing it in the README fails
    ;; here, keeping the 'these files and no others' claim honest.
    (let [base        (.toPath (.getCanonicalFile (scaffold-dir)))
          allowed     (into #{"README.md" ".gitignore"} (manifest))
          ;; Generated by npm install / shadow compile — all gitignored, none
          ;; committed (see the scaffold's .gitignore). Excluded so a dev
          ;; checkout that has already built does not trip the census.
          ignored-top #{"node_modules" ".shadow-cljs" ".cpcache" "out"}
          ignored-file #{"package-lock.json"}
          on-disk     (->> (file-seq (scaffold-dir))
                           (filter #(.isFile ^java.io.File %))
                           (map #(-> base
                                     (.relativize (.toPath (.getCanonicalFile ^java.io.File %)))
                                     (.toString)
                                     (str/replace "\\" "/")))
                           ;; drop generated trees + generated bundle output
                           (remove (fn [p]
                                     (or (contains? ignored-top (first (str/split p #"/" 2)))
                                         (contains? ignored-file p)
                                         (str/starts-with? p "resources/public/js/"))))
                           set)]
      (is (= allowed on-disk)
          (str "scaffold tree diverged from README manifest.\n"
               "  unexpected (on disk, not documented): " (sort (remove allowed on-disk)) "\n"
               "  missing   (documented, not on disk):  " (sort (remove on-disk allowed)))))))

(def ^:private contract-keys [:build-defaults])

(defn- read-config
  "Read a shadow-cljs.edn as data. `:default` absorbs the build-tool reader tags
  (`#shadow/env`) that appear in the monorepo's own config."
  [file]
  (edn/read-string {:default (fn [_tag v] v)} (slurp file)))

(deftest shadow-config-carries-the-one-load-bearing-setting
  ;; spec/004C-Roots-and-Mount.md §2.1.1: the build hook is load-bearing on
  ;; Shadow. The old top-level :cache-blockers tax was removed at the S6 cut-over
  ;; (rf2-u53yy.1) — the registries are harvested from cache-durable analyzer
  ;; data, so a warm daemon reuses the disk cache and no blocker is needed.
  ;;
  ;; rf2-vxgfnd.196 — DERIVED, not restated. This test used to spell the setting
  ;; as a string literal, which made it a copy of the rule checking itself: edit
  ;; the real configuration and this stayed green. The expected value is now the
  ;; monorepo's own shadow-cljs.edn, read at run time, so the scaffold is pinned
  ;; to what the framework actually configures.
  (let [real (select-keys (read-config (io/file @root "implementation/shadow-cljs.edn"))
                          contract-keys)]
    ;; Shape guard first: if the framework config lost the setting, both sides
    ;; would be {} and the comparison would pass vacuously.
    (is (= (set contract-keys) (set (keys real)))
        (str "implementation/shadow-cljs.edn no longer carries the build-hook "
             "setting; found " (sort (keys real))))
    (is (not (contains? (read-config (io/file @root "implementation/shadow-cljs.edn"))
                        :cache-blockers))
        "implementation/shadow-cljs.edn must NOT carry the removed :cache-blockers tax")
    (is (= real (select-keys (read-config (scaffold-file "shadow-cljs.edn"))
                             contract-keys))
        (str "the scaffold's shadow-cljs.edn diverged from the framework's own "
             "re-frame.ui configuration — a consumer copying this scaffold would "
             "not configure re-frame.ui the way this repo actually does"))))

(deftest host-page-wires-the-mount-target-and-bundle
  (let [html (slurp (scaffold-file "resources/public/index.html"))]
    (is (re-find #"id=\"root\"" html)
        "index.html lost the id=\"root\" node that ui/mount targets")
    (is (re-find #"<script[^>]*src=\"[^\"]*/js/main\.js\"" html)
        "index.html no longer loads the compiled /js/main.js bundle")))

(deftest deps-local-root-coords-resolve
  (testing "the committed :local/root paths point at real framework artefacts"
    (let [deps  (slurp (scaffold-file "deps.edn"))
          roots (map second (re-seq #":local/root\s+\"([^\"]+)\"" deps))]
      (is (= 2 (count roots))
          "deps.edn should carry exactly the two framework :local/root coords")
      (doseq [rel roots]
        (is (.isFile (io/file (scaffold-dir) rel "deps.edn"))
            (str "deps.edn :local/root " rel " does not resolve to a framework artefact"))))))

;; ---------------------------------------------------------------------------
;; COMPILE tier — env-gated
;; ---------------------------------------------------------------------------

(def ^:private compile-tier? (= "1" (System/getenv "RF2_UI_SCAFFOLD_COMPILE")))

(def ^:private windows?
  (str/starts-with? (str/lower-case (System/getProperty "os.name")) "windows"))

(defn- sh!
  "Run a shell command in `dir`, combining stdout+stderr. {:exit :out}."
  [dir cmd]
  (let [pb (ProcessBuilder. ^java.util.List
                            (if windows? ["cmd" "/c" cmd] ["sh" "-c" cmd]))]
    (.directory pb (io/file dir))
    (.redirectErrorStream pb true)
    (let [proc (.start pb)
          out  (slurp (.getInputStream proc))
          done (.waitFor proc (long 15) java.util.concurrent.TimeUnit/MINUTES)]
      (when-not done (.destroyForcibly proc))
      {:exit (if done (.exitValue proc) ::timeout) :out out})))

(defn- delete-tree! [^java.io.File f]
  (doseq [c (reverse (file-seq f))] (.delete ^java.io.File c)))

(defn- abs-forward [^java.io.File f]
  (str/replace (.getCanonicalPath f) "\\" "/"))

(defn- materialize!
  "Copy `files` (a subset of the manifest) from the scaffold into a fresh temp
   dir. deps.edn's :local/root coords are rewritten from scaffold-relative to
   absolute so the relocated tree still resolves the framework — the ONLY
   edit; every other byte is verbatim (the emitted_test_run precedent)."
  [files]
  (let [tmp (.toFile (java.nio.file.Files/createTempDirectory
                       "ui-scaffold-smoke"
                       (make-array java.nio.file.attribute.FileAttribute 0)))]
    (doseq [rel files]
      (let [src (scaffold-file rel)
            dst (io/file tmp rel)]
        (io/make-parents dst)
        (if (= rel "deps.edn")
          (spit dst (reduce (fn [s r]
                              (str/replace s (str "\"" r "\"")
                                           (str "\"" (abs-forward (io/file (scaffold-dir) r)) "\"")))
                            (slurp src)
                            (map second (re-seq #":local/root\s+\"([^\"]+)\"" (slurp src)))))
          (io/copy src dst))))
    tmp))

(defn- host-ok?
  "The runnable-app contract that `shadow-cljs compile` alone cannot check:
   a host page with the mount node and the bundle script."
  [dir]
  (let [html (io/file dir "resources/public/index.html")]
    (and (.isFile html)
         (let [s (slurp html)]
           (and (re-find #"id=\"root\"" s)
                (re-find #"/js/main\.js" s))))))

(defn- build-ok?
  "npm install, then a real Shadow compile. Hermetic: if the npm deps did not
   materialize (e.g. package.json is the omitted file) we do NOT let npx reach
   out to the registry — no local shadow-cljs means not buildable."
  [dir]
  (let [install (sh! dir "npm install --no-audit --no-fund")]
    (and (zero? (:exit install))
         (.isDirectory (io/file dir "node_modules/shadow-cljs"))
         (.isDirectory (io/file dir "node_modules/react"))
         (let [c (sh! dir "npx shadow-cljs compile app")]
           (and (zero? (:exit c))
                (.isFile (io/file dir "resources/public/js/main.js")))))))

(defn- viable?
  "A scaffold tree is viable when the host page is wired AND it compiles.
   host-ok? is checked first so an index.html-omitted tree short-circuits
   without paying for a (successful) compile."
  [dir]
  (and (host-ok? dir) (build-ok? dir)))

(deftest ^:compile scaffold-installs-and-compiles
  (if-not compile-tier?
    (is true "COMPILE tier skipped (set RF2_UI_SCAFFOLD_COMPILE=1 to run the install+compile proof)")
    (let [tmp (materialize! (manifest))]
      (try
        (let [install (sh! tmp "npm install --no-audit --no-fund")]
          (is (zero? (:exit install))
              (str "npm install failed on the documented files alone:\n" (:out install))))
        (let [c (sh! tmp "npx shadow-cljs compile app")]
          (is (zero? (:exit c))
              (str "npx shadow-cljs compile app failed on the documented files alone:\n" (:out c)))
          (is (.isFile (io/file tmp "resources/public/js/main.js"))
              "compile reported success but produced no resources/public/js/main.js"))
        (finally (delete-tree! tmp))))))

(deftest ^:compile omitting-any-load-bearing-file-breaks-the-scaffold
  (if-not compile-tier?
    (is true "COMPILE tier skipped (set RF2_UI_SCAFFOLD_COMPILE=1 to run the omission matrix)")
    (let [files (manifest)]
      (doseq [omit files]
        (testing (str "without " omit)
          (let [tmp (materialize! (remove #{omit} files))]
            (try
              (is (not (viable? tmp))
                  (str "the scaffold still stood up without " omit
                       " — so it is not a load-bearing file, and the README manifest overstates the requirement"))
              (finally (delete-tree! tmp)))))))))
