#!/usr/bin/env python3
"""Generate placeholder PNGs for the Xray + Story tutorials.

These are committed so the docs site builds cleanly even without re-running
the live Playwright capture pipeline (`generate-tutorial-screenshots.cjs`).

Running the Playwright pipeline overwrites these with the real captures.

Each placeholder paints:
  - The expected output filename in large text
  - The descriptive caption in smaller text
  - A coloured strip identifying xray vs story

The PIL/Pillow runtime ships with the standard MkDocs/CI Python environment.

Usage (from repo root):
    python docs/scripts/generate-placeholder-images.py
"""

from __future__ import annotations

import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont


REPO_ROOT = Path(__file__).resolve().parents[2]
OUT_XRAY = REPO_ROOT / "docs" / "images" / "xray"
OUT_STORY = REPO_ROOT / "docs" / "images" / "story"

# (tool, filename, caption)
# Filenames track docs/scripts/generate-tutorial-screenshots.cjs scene
# outputs. The Playwright pipeline overwrites these placeholders with
# real captures (annotated per docs/scripts/tutorial-annotation-spec.json).
PLACEHOLDERS = [
    # Xray tutorial captures (this generator is the fallback for fresh
    # checkouts before someone runs Playwright):
    ("xray", "01-floating-pill.png",   "The Xray floating pill on the live counter app"),
    ("xray", "02-shell-opened.png",    "The Xray shell, opened over the live app"),
    ("xray", "02-sidebar-panels.png",  "Sixteen panels in three bands"),
    ("xray", "02-event-detail.png",    "Event detail — the landing panel"),
    ("xray", "03-time-travel.png",     "Time-travel scrubber with epoch history"),
    ("xray", "04-trace.png",           "Trace panel with live event count + filter bar"),
    ("xray", "05-dom-attribute.png",   "data-rf2-source-coord on every rendered element"),
    ("xray", "08-machines.png",        "Machine inspector with state-chart"),
    ("xray", "09-app-db-diff.png",     "App-DB diff for a cascade"),
    # Additional Xray scenes — the AI co-pilot lives at ch 10; the
    # conditional-band chapters shifted one slot down to absorb the move:
    ("xray", "10-copilot-rail.png",    "AI co-pilot rail — pull-only, slash commands"),
    ("xray", "06-schema-timeline.png", "Schema-violation timeline — dot per epoch"),
    ("xray", "07-hydration.png",       "Hydration debugger — server vs client trees"),
    ("xray", "09-app-db-modes.png",    "App-DB diff — three rendering modes"),

    # Story tutorial captures are generated by
    # docs/scripts/generate-story-tutorial-screenshots.cjs and committed as
    # docs/images/story/story-tutorial-*.png, so no Story placeholders are
    # generated here.
]

SIZE = (1280, 800)
COLOURS = {
    "xray": ("#0d47a1", "#bbdefb"),  # blue band, light blue body
    "story": ("#1b5e20", "#c8e6c9"),  # green band, light green body
}


# Per-OS TrueType candidates, ordered most-likely-present first. The
# running platform's list is tried first; the others follow as defensive
# fallbacks (e.g. a Linux box with a macOS font mounted). Every entry is a
# common system path or font directory — no single hardcoded path is load-
# bearing, and the PIL default backstops any platform with none of these.
_FONT_CANDIDATES = {
    "win32": [
        "C:/Windows/Fonts/segoeui.ttf",
        "C:/Windows/Fonts/arial.ttf",
        "C:/Windows/Fonts/calibri.ttf",
        "C:/Windows/Fonts/tahoma.ttf",
    ],
    "darwin": [
        "/System/Library/Fonts/Helvetica.ttc",
        "/System/Library/Fonts/HelveticaNeue.ttc",
        "/System/Library/Fonts/Supplemental/Arial.ttf",
        "/Library/Fonts/Arial.ttf",
        str(Path.home() / "Library" / "Fonts" / "Arial.ttf"),
    ],
    # Linux + other POSIX: distro font trees plus the user font dir.
    "linux": [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
        "/usr/share/fonts/truetype/freefont/FreeSans.ttf",
        "/usr/share/fonts/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/liberation/LiberationSans-Regular.ttf",
        str(Path.home() / ".fonts" / "DejaVuSans.ttf"),
        str(Path.home() / ".local" / "share" / "fonts" / "DejaVuSans.ttf"),
    ],
}


def _ordered_candidates() -> list[str]:
    """Candidate font paths, the running OS first then the rest as fallbacks."""
    if sys.platform.startswith("win"):
        primary = "win32"
    elif sys.platform == "darwin":
        primary = "darwin"
    else:
        primary = "linux"  # treat all other POSIX platforms as Linux-like
    ordered = list(_FONT_CANDIDATES[primary])
    for key, paths in _FONT_CANDIDATES.items():
        if key != primary:
            ordered.extend(paths)
    return ordered


def find_font(size: int) -> ImageFont.ImageFont:
    """Resolve a TrueType font cross-platform.

    Tries the running OS's common font locations first, then the other
    platforms' as defensive fallbacks. When no TrueType is found anywhere
    (e.g. a minimal CI image), degrades gracefully to PIL's bundled default
    so the script never hard-fails on a missing platform path.
    """
    for path in _ordered_candidates():
        if Path(path).exists():
            return ImageFont.truetype(path, size)
    # Final fallback: PIL's bundled default. Pillow >= 10.1 honours `size`
    # (older builds ignore it but still return a usable font).
    try:
        return ImageFont.load_default(size=size)
    except TypeError:
        return ImageFont.load_default()


def draw_placeholder(out: Path, caption: str, tool: str) -> None:
    band_colour, body_colour = COLOURS[tool]
    img = Image.new("RGB", SIZE, body_colour)
    draw = ImageDraw.Draw(img)

    # Top band
    draw.rectangle([0, 0, SIZE[0], 96], fill=band_colour)
    band_font = find_font(40)
    label = f"{tool.upper()}  ·  {out.name}"
    draw.text((48, 26), label, fill="#ffffff", font=band_font)

    # Body — caption + "screenshot placeholder" subtitle
    caption_font = find_font(36)
    draw.text((48, 160), caption, fill="#212121", font=caption_font)

    sub_font = find_font(22)
    draw.text(
        (48, 220),
        "Placeholder. Re-run docs/scripts/generate-tutorial-screenshots.cjs",
        fill="#424242",
        font=sub_font,
    )
    draw.text(
        (48, 252),
        "against a live dev build to replace with the real capture.",
        fill="#424242",
        font=sub_font,
    )

    # Centerpiece box mimicking the panel-shape
    draw.rectangle([200, 360, 1080, 700], outline=band_colour, width=4)
    centre_font = find_font(54)
    centre_text = caption.split(" — ")[0][:40]
    bbox = draw.textbbox((0, 0), centre_text, font=centre_font)
    text_w = bbox[2] - bbox[0]
    text_h = bbox[3] - bbox[1]
    draw.text(
        ((SIZE[0] - text_w) / 2, (SIZE[1] - text_h) / 2 + 60),
        centre_text,
        fill=band_colour,
        font=centre_font,
    )

    out.parent.mkdir(parents=True, exist_ok=True)
    img.save(out, optimize=True)


def main() -> int:
    for tool, name, caption in PLACEHOLDERS:
        out = (OUT_XRAY if tool == "xray" else OUT_STORY) / name
        draw_placeholder(out, caption, tool)
        print(f"OK  {out.relative_to(REPO_ROOT)}")
    print(f"\nGenerated {len(PLACEHOLDERS)} placeholders.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
