(ns re-frame2-pair-mcp.tools.get-re-frame2-pair-instructions
  "Tool: get-re-frame2-pair-instructions — agent-onboarding text.

  Mirrors story-mcp's `get-story-instructions`. Returns an inline
  prose summary of re-frame2-pair-mcp's tool catalogue + the conventions an
  agent needs to drive the surface effectively (EDN posture,
  `:origin :pair` tagged mutations, streaming subscribe semantics,
  the wire-boundary cap + dedup + elision pipeline).

  `instructions-text` ships inline as a single string so the artefact
  is self-contained — no resource read at boot, one MCP frame, zero
  socket bytes. The structural peer in story-mcp
  (`story-instructions-text` in `re-frame.story-mcp.tools.dev`) uses
  the same inline-`(str ...)` shape, kept aligned so AI pairs reading
  both servers see one answer to the onboarding-text question."
  (:require [re-frame2-pair-mcp.tools.wire :as wire]))

(def instructions-text
  "Inline onboarding prose. Inline `(str ...)` of `\\n`-glued lines —
  see the ns docstring for the rationale (mirrors story-mcp). Edit
  this string when the catalogue changes; the docstring on
  `re-frame2-pair-mcp.tools/tool-descriptors` is the structural peer."
  (str
    "re-frame2-pair-mcp agent quick reference.\n"
    "Full spec: tools/re-frame2-pair-mcp/spec/003-Tool-Catalogue.md.\n"
    "\n"
    "## What this server is\n"
    "\n"
    "An MCP stdio server that pair-programs with a live re-frame2 app\n"
    "over a persistent nREPL socket. The agent host (Claude Code /\n"
    "Cursor / Copilot) launches it as a subprocess; one connection\n"
    "lives for the session; each tool routes through one of the\n"
    "eight Tool-Pair primitives on the runtime side.\n"
    "\n"
    "## Tool catalogue\n"
    "\n"
    "  discover-app          — verify nREPL + preloaded runtime; run first.\n"
    "  orient                — app-shape orientation in one round-trip: liveness,\n"
    "                          frames (all / app / operating), per-app-frame\n"
    "                          app-db top-keys, registrar counts + high-value\n"
    "                          ids, machines. First-contact on an unfamiliar app\n"
    "                          (rf2-3bu3d.8); drill via list-handlers / snapshot.\n"
    "  eval-cljs             — eval a CLJS form; returns the EDN value.\n"
    "                          Optional :frame arg (rf2-ntuzf) wraps the form\n"
    "                          in (re-frame.core/with-frame ...) for multi-\n"
    "                          frame apps.\n"
    "  dispatch              — fire an event tagged :origin :pair. Surfaces a\n"
    "                          :cascade-summary slot (rf2-6yqdl) projecting\n"
    "                          what happened — :db-diff, :fx-fired, :outcome,\n"
    "                          :elapsed-ms, etc. One round-trip, no\n"
    "                          watch-epochs correlation needed. Optional\n"
    "                          :frame arg (e.g. \":rf/xray\") targets a named\n"
    "                          frame in a multi-frame app; an untargetable\n"
    "                          frame returns a structured error, never a\n"
    "                          {:mode ...} no-op (rf2-ldfnx).\n"
    "  dispatch-dry-run      — simulate a cascade WITHOUT committing\n"
    "                          (rf2-17hvp). Full reducer + interceptor chain\n"
    "                          run, schema validation fires, machine\n"
    "                          transitions simulate — but NO fx execute and\n"
    "                          the app-db rolls back. :would-fire-effects\n"
    "                          enumerates what WOULD have fired. NOT --allow-\n"
    "                          writes-gated; the contract IS 'no observable\n"
    "                          effect'.\n"
    "  restore-epoch         — time-travel undo; rewind a frame to a prior\n"
    "                          epoch (gated behind --allow-writes). Surfaces a\n"
    "                          :cascade-summary + :unreplayable-effects vector\n"
    "                          (rf2-6yqdl) listing fx the original cascade\n"
    "                          fired that the restore cannot undo.\n"
    "  replace-app-db        — state injection; replace a frame's app-db\n"
    "                          with EDN data (gated behind --allow-writes).\n"
    "  trace-window          — epochs in the last N ms (cursor-paginated).\n"
    "  watch-epochs          — pull-mode poll for matching epochs.\n"
    "  tail-build            — wait for a hot-reload to land.\n"
    "  snapshot              — coarse per-frame mega-read (app-db, subs,\n"
    "                          machines, epochs, traces).\n"
    "  get-path              — read a single value at `path` from a\n"
    "                          frame's app-db.\n"
    "  read-sub              — validated one-shot subscription read (rf2-3bu3d.7):\n"
    "                          derefs a registered sub for a frame and returns its\n"
    "                          value; unknown sub-id returns :nearest matches, not\n"
    "                          a silent nil. Prefer over raw eval-cljs subscribe.\n"
    "  read-dom              — view-plane read; querySelectorAll → per-node\n"
    "                          {:tag :text :attrs} EDN (read-only,\n"
    "                          text/node-capped; rf2-nfjil).\n"
    "  read-ui               — typed ui/read (rf2-3bu3d.1): given a view-id / point\n"
    "                          / selector, return the rendered subtree (elided) PLUS\n"
    "                          the producing re-frame2 :entity (view-id + source-coord)\n"
    "                          in one round-trip. The complement to read-dom — no\n"
    "                          testids needed; rides the view<->DOM map.\n"
    "  record                — install a background signal recorder and\n"
    "                          return a :recording-id; the human interacts\n"
    "                          while it samples (rf2-zo4b9).\n"
    "  read-recording        — read back a recorder's change-log. :drain\n"
    "                          consumes the buffer (poll → consume → repeat);\n"
    "                          :stop reads-and-closes (rf2-zo4b9).\n"
    "  watch-until           — block until a predicate over a signal-set\n"
    "                          holds (or :timeout-ms elapses; rf2-zo4b9).\n"
    "  subscribe             — streaming subscription; emits each batch\n"
    "                          as a notifications/progress.\n"
    "  unsubscribe           — close a streaming subscription.\n"
    "  list-subscriptions    — list the LIVE reactive sub-cache for a frame\n"
    "                          (matches snapshot :sub-cache; rf2-qicji).\n"
    "                          Optional :frame / :include-values.\n"
    "  list-streams          — list active streaming-tap subscriptions +\n"
    "                          queue stats (the streaming diagnostic\n"
    "                          list-subscriptions formerly carried).\n"
    "  get-stream-controls   — report SERVER-SIDE streaming resource-control\n"
    "                          state: effective caps, active slots vs limit,\n"
    "                          token-bucket pressure, abuse-window count. The\n"
    "                          'why was my stream denied / quiet / terminated?'\n"
    "                          diagnostic (rf2-a0kxsb). In-process, no nREPL —\n"
    "                          answers even when the runtime is down. Cross-check\n"
    "                          :active against list-streams for leaked slots.\n"
    "  handler-meta          — return :source-coord + :doc + :tags for a\n"
    "                          registered handler (event / sub / fx / cofx /\n"
    "                          interceptor / view / frame / route / flow /\n"
    "                          head / error-projector / machine).\n"
    "  list-handlers         — enumerate every registered id under a kind\n"
    "                          (the discovery peer of handler-meta). Pass\n"
    "                          :frame to enumerate that frame's image-resolved\n"
    "                          ids (EP-0023).\n"
    "  describe-image        — describe a frame's running image generation —\n"
    "                          composed images, kinds, capability requires,\n"
    "                          per-kind counts (+ :include-ns provenance). The\n"
    "                          'what behaviour does this frame run, and where\n"
    "                          did each piece come from?' read (rf2-srobm0).\n"
    "  set-operating-frame   — pin the session's operating frame — the frame\n"
    "                          frame-targeted ops (dispatch, snapshot, get-path,\n"
    "                          read-sub, …) resolve to without a per-call :frame.\n"
    "                          The escape from :ambiguous-frame in multi-frame apps\n"
    "                          (rf2-zomfq).\n"
    "  reset-operating-frame — clear the session operating-frame pin; targeted ops\n"
    "                          revert to sole-frame / :ambiguous-frame resolution.\n"
    "                          Idempotent (rf2-zomfq).\n"
    "  get-operating-frame   — report the operating-frame triple {:frames :selected\n"
    "                          :operating} (:operating nil = ambiguous). Pure read;\n"
    "                          call to see what targeted ops resolve to (rf2-zomfq).\n"
    "  get-re-frame2-pair-instructions — this text.\n"
    "\n"
    "## EDN posture\n"
    "\n"
    "Every tool returns `{:content [{:type \"text\" :text <edn-string>}]}`.\n"
    "The `:text` slot is `pr-str`-rendered EDN — read with\n"
    "`clojure.edn/read-string` or its target-language peer. JSON-shaped\n"
    "tools/list args are parsed as EDN when sensible (e.g. `:path` accepts\n"
    "an EDN-encoded vector string or a JSON array).\n"
    "\n"
    "## Tagged mutations\n"
    "\n"
    "`dispatch` and `eval-cljs` tag their side-effects with `:origin :pair`\n"
    "(or `:origin :pair-mcp` where the runtime distinguishes) so the agent\n"
    "host's mutations are distinguishable from user-driven events in the\n"
    "epoch ring. Filter your `subscribe` / `watch-epochs` calls on\n"
    "`:origin :pair` to see only what you triggered.\n"
    "\n"
    "## Wire-boundary pipeline\n"
    "\n"
    "Every response passes through (in order): precheck cache → size\n"
    "elision → diff-encode (epochs) → structural dedup → wire-cap. Each\n"
    "stage has a per-tool knob — pass `dedup false` / `elision false` /\n"
    "`max-tokens 0` to bypass the respective stage. Over-cap responses\n"
    "return the `:rf.mcp/overflow` marker; declared-large slots return\n"
    "the `:rf.size/large-elided` marker with a `:handle [:rf.elision/at\n"
    "<path>]` fetch handle.\n"
    "\n"
    "## Streaming subscribe semantics\n"
    "\n"
    "`subscribe` is a long-running tools/call. Each batch of matching\n"
    "events arrives as a `notifications/progress` notification correlated\n"
    "by the call's `progressToken`. The call resolves with a summary when\n"
    "the client cancels or `unsubscribe` fires. Topics: `trace`, `epoch`,\n"
    "`fx`, `error`. Filter vocab is topic-dependent — see the descriptor.\n"
    "Per-tick `:events` vectors are structurally deduped; oversize tick\n"
    "payloads honour the wire-cap.\n"
    "\n"
    "## Session entry-point\n"
    "\n"
    "Call `discover-app` first every session — it verifies the nREPL\n"
    "socket, confirms the `re-frame2-pair.runtime` preload landed, and\n"
    "surfaces warnings (debug disabled, no frames, ambiguous frame,\n"
    "missing source-coord annotation). A health-check before the first\n"
    "real op short-circuits a class of confusing downstream errors.\n"))

(defn get-re-frame2-pair-instructions-tool
  "Return the agent-onboarding text. `conn` and `args` are accepted
  for shape uniformity with the other tool handlers but ignored —
  the text is inline and the call carries no per-request state."
  [_conn _args]
  (js/Promise.resolve
    (wire/ok-text {:ok? true
                   :tool "get-re-frame2-pair-instructions"
                   :text instructions-text})))
