(ns re-frame.http.machine-wrapper
  "Machine-shape wrapper for `:rf.http/managed` (rf2-ijm7).

  Extracted from `re-frame.http.managed` per rf2-3i9b. Per Spec 014
  §Machine-shape wrapper: `:rf.http/managed` ALSO registers as a child-
  invokable state machine, so a parent machine can write

    {:spawn {:machine-id :rf.http/managed
              :data       {:request {:method :get :url \"/api/me\"}}}
     :on     {:succeeded :authenticated
              :failed    :login}}

  and the wrapper:
    1. issues the request on entry to its `:requesting` state,
    2. transitions to `:succeeded` / `:failed` on the reply,
    3. dispatches `[<parent-id> [:succeeded value]]` (or
       `[<parent-id> [:failed failure]]`) back to the parent, where
       `<parent-id>` and `<self-id>` come from spawn-fx's framework-
       reserved injection into the actor's initial `:data` per
       rf2-ijm7 (`:rf/parent-id`, `:rf/self-id`).

  The wrapper machine is registered via the `:machines/reg-machine`
  late-bind hook: re-frame.http.managed must NOT statically `:require`
  re-frame.machines (per rf2-xbtj the machines artefact is optional)
  and re-frame.machines must NOT statically `:require`
  re-frame.http.managed (per rf2-5kpd the http artefact is optional).
  When the machines artefact is absent the wrapper registration is
  skipped; the existing `:rf.http/managed` fx continues to work
  unchanged (the wrapper is purely additive on top of the fx surface).

  The fx (kind `:fx`) and the machine (kind `:event`) coexist under
  the same id `:rf.http/managed` — re-frame.registrar segregates by
  kind, so `:fx [[:rf.http/managed args]]` continues to fire the fx
  AND `{:spawn {:machine-id :rf.http/managed ...}}` resolves to the
  machine.

  ## Where the canned-stub handlers live (rf2-w59es5)

  The canned-stub handler bodies (`canned-success-handler` /
  `canned-failure-handler` and their `emit-canned-*!` / `run-request-
  chain` / `dispatch-canned-reply!` helpers) are TEST scaffolding — they
  live in `re-frame.http.test-support` alongside the canned-stub fx
  registrations and the `with-managed-request-stubs*` helper that
  composes against them. They used to share this production-loaded
  namespace (so the stub macros could reach them without a circular
  require); that constraint no longer holds now that the stub macros and
  the stub fx registrations have consolidated into `http-test-support`
  (rf2-lwmgw), so the stub bodies moved there. This namespace is
  production-loaded (by `re-frame.http.managed`) and now carries ONLY the
  machine-shape wrapper."
  (:require [re-frame.late-bind :as late-bind]))

;; ---- machine-shape wrapper spec (rf2-ijm7) --------------------------------

(defn http-managed-machine-spec
  "Return the machine-shape wrapper spec for `:rf.http/managed`.

  The spec is regenerated by the registration form below (rather than
  defined as a static literal) so the action closures' calls into
  `re-frame.late-bind/get-fn` resolve at call time — preserving the
  late-bind discipline that lets the machines artefact be optional.

  Per Spec 014 §Machine-shape wrapper:
   - `:initial :requesting` — entry happens on spawn-time
     `[:rf.machine.spawn/spawned]` (the synthetic event the runtime dispatches
     to spawns without an explicit `:start`; per Spec 005 §Spawning).
   - The wrapper's `:data` carries the args map for the underlying
     `:rf.http/managed` fx PLUS the framework-reserved
     `:rf/parent-id` / `:rf/self-id` keys (stamped by spawn-fx, per
     rf2-ijm7).
   - `:fire-request` builds an args map for the underlying fx,
     overriding `:on-success` / `:on-failure` so the reply lands back
     at the wrapper actor as `[:rf.http/succeeded value]` /
     `[:rf.http/failed failure]`.
   - `:succeeded` / `:failed` are terminal leaf states; their
     `:entry` dispatches the parent's `[:succeeded value]` or
     `[:failed failure]`. When `:rf/parent-id` is nil (direct dispatch
     of `[:rf.http/managed ...]` to the wrapper rather than `:spawn`
     spawning), the parent-dispatch is a benign no-op."
  []
  {:doc "Spec 014 — :rf.http/managed as a child-invokable state machine.

         Wraps the :rf.http/managed fx in a machine envelope. Use via
         `:spawn {:machine-id :rf.http/managed :data {:request {...}}}`
         on a parent machine's state node. The wrapper runs the request
         on entry, transitions to :succeeded / :failed on the reply,
         and dispatches `[<parent-id> [:succeeded value]]` (or :failed)
         back to the parent."
   :initial :requesting
   :states
   {:requesting
    ;; Initial-state `:entry` actions fire on spawn as part of the
    ;; bootstrap cascade — the canonical re-frame2 shape for "do this
    ;; when the actor first runs".
    {:entry :fire-request
     :on    {:rf.http/succeeded  {:target :succeeded :action :record-value}
             :rf.http/failed     {:target :failed    :action :record-failure}}}

    :succeeded
    {:entry :dispatch-done
     :meta  {:terminal? true}}

    :failed
    {:entry :dispatch-error
     :meta  {:terminal? true}}}

   :actions
   {:fire-request
    (fn [{data :data}]
      ;; Build the args map for the underlying fx from whatever the
      ;; user passed through the parent's :spawn :data. Strip the
      ;; framework-reserved `:rf/*` keys; pass through every other
      ;; documented arg (Spec 014 §The args map) so the wrapper is a
      ;; transparent envelope around the fx surface.
      (let [self-id   (:rf/self-id data)
            fx-args   (-> data
                          (dissoc :rf/self-id :rf/parent-id :rf/invoke-id)
                          (assoc :on-success [self-id [:rf.http/succeeded]]
                                 :on-failure [self-id [:rf.http/failed]]))]
        {:fx [[:rf.http/managed fx-args]]}))

    :record-value
    (fn [{data :data [_ payload] :event}]
      {:data (assoc data :rf/result payload)})

    :record-failure
    (fn [{data :data [_ payload] :event}]
      {:data (assoc data :rf/result payload)})

    :dispatch-done
    (fn [{data :data}]
      (let [parent-id (:rf/parent-id data)
            result    (:rf/result data)
            value     (:value result)]
        (when parent-id
          {:fx [[:dispatch [parent-id [:succeeded value]]]]})))

    :dispatch-error
    (fn [{data :data}]
      (let [parent-id (:rf/parent-id data)
            result    (:rf/result data)
            ;; rf2-ibksxg — the reply payload is the canonical envelope; the
            ;; classified `:rf.http/*` failure map rides under `:error`
            ;; (`:status :error` / `:cancelled`), not the retired `:failure`.
            failure   (:error result)]
        (when parent-id
          {:fx [[:dispatch [parent-id [:failed failure]]]]})))}})

(defn register-managed-machine!
  "Register the `:rf.http/managed` machine-shape wrapper via the
  `:machines/reg-machine` late-bind hook. Returns the registered
  machine-id on success, or nil if the machines artefact is not on the
  classpath (in which case the existing fx-only surface is unaffected)."
  []
  (when-let [reg-machine* (late-bind/get-fn :machines/reg-machine)]
    (reg-machine* :rf.http/managed (http-managed-machine-spec))
    :rf.http/managed))
