(ns re-frame.http.machine-wrapper
  "Machine-shape wrapper for `:rf.http/managed`.

  Per Spec 014 §Machine-shape wrapper, `:rf.http/managed` also registers as a child-
  invokable state machine, so a parent machine can write

    {:spawn {:machine-id :rf.http/managed
              :data       {:request {:url \"/api/me\" :method :get}}}
     :on     {:succeeded :authenticated
              :failed    :login}}

  and the wrapper:
    1. issues the request on entry to its `:requesting` state,
    2. transitions to `:succeeded` / `:failed` on the reply — both `:final?`
       leaves whose `:output-key` is `:rf/result`, so the wrapper completes
       the way every child machine does (Spec 005 §Child completion protocol),
    3. under a `:spawn` parent, dispatches `[<parent-id> [:succeeded value]]`
       (or `[<parent-id> [:failed failure]]`) back to the parent, where
       `<parent-id>` and `<self-id>` come from spawn-fx's framework-
       reserved injection into the actor's initial `:data`
       (`:rf/parent-id`, `:rf/self-id`). Under a `:spawn-all` parent the
       finality alone folds into the join (see `:dispatch-done`).

  The wrapper machine is registered via the `:machines/reg-machine`
  late-bind hook: neither optional artefact statically requires the other.
  When the machines artefact is absent the wrapper registration is
  skipped; the existing `:rf.http/managed` fx continues to work
  unchanged (the wrapper is purely additive on top of the fx surface).

  The fx (kind `:fx`) and the machine (kind `:event`) coexist under
  the same id `:rf.http/managed` — re-frame.registrar segregates by
  kind, so `:fx [[:rf.http/managed args]]` continues to fire the fx
  AND `{:spawn {:machine-id :rf.http/managed ...}}` resolves to the
  machine.

  ## Test support

  The canned-stub handler bodies (`canned-success-handler` /
  `canned-failure-handler` and their `emit-canned-*!` / `run-request-
  chain` / `dispatch-canned-reply!` helpers) are TEST scaffolding — they
  live in `re-frame.http.test-support` alongside the canned-stub fx
  registrations and the `with-request-stubs` helper that
  composes against them. This production-loaded namespace carries only the
  machine wrapper."
  (:require [re-frame.late-bind :as rf.late-bind]))

;; ---- machine-shape wrapper spec -------------------------------------------

(defn- parent-to-notify
  "The parent a terminal state's `:entry` should dispatch to, or nil.

  Only a `:spawn` child notifies its parent by event. A `:spawn-all` child
  carries the runtime's `:rf/join-child` membership record, and completes
  through finality alone: the finalize cascade mints the join's completion
  carrier from `:output-key`. A `:final?` state's `:entry` still runs (Spec 005
  §Final states §Composition with `:entry` / `:exit`), so without this gate a
  join child would ALSO send `[:succeeded value]` into its parent — a spurious
  event that a parent carrying the single-`:spawn` `:on {:succeeded …}` habit
  transitions on, exiting its `:spawn-all` state and tearing down its own join
  (rf2-6gxs)."
  [data]
  (when (nil? (:rf/join-child data))
    (:rf/parent-id data)))

(defn http-managed-machine-spec
  "Return the machine-shape wrapper spec for `:rf.http/managed`.

  The spec is regenerated by the registration form below (rather than
  defined as a static literal) so the action closures' calls into
  `re-frame.late-bind/get-fn` resolve at call time — preserving the
  late-bind discipline that lets the machines artefact be optional.

  Per Spec 014 §Machine-shape wrapper:
   - `:initial :requesting` — entry happens on spawn-time
     `[:rf.machine.spawn/spawned]` (the synthetic event the runtime dispatches
     to spawns without an explicit `:start`; per Spec 005 §Spawning).
   - The wrapper's `:data` carries the args map for the underlying
     `:rf.http/managed` fx PLUS the framework-reserved
     `:rf/parent-id` / `:rf/self-id` keys stamped by spawn-fx.
   - `:fire-request` builds an args map for the underlying fx,
     overriding `:on-success` / `:on-failure` so the reply lands back
     at the wrapper actor as `[:rf.http/succeeded reply]` /
     `[:rf.http/failed reply]`.
   - `:record-value` / `:record-failure` store the ONE value a parent sees —
     `(:value reply)` / `(:error reply)` — under `:rf/result`.
   - `:succeeded` / `:failed` are `:final?` leaves with `:output-key
     :rf/result` (`:failed` also `:error? true`), so a `:spawn-all` join
     resolves on them. Their `:entry` dispatches the parent's
     `[:succeeded value]` / `[:failed failure]` for a `:spawn` child only;
     when `:rf/parent-id` is nil (direct dispatch of `[:rf.http/managed ...]`
     to the wrapper rather than `:spawn` spawning), the parent-dispatch is a
     benign no-op."
  []
  {:doc "Spec 014 — :rf.http/managed as a child-invokable state machine.

         Wraps the :rf.http/managed fx in a machine envelope. Use via
         `:spawn {:machine-id :rf.http/managed :data {:request {...}}}`
         on a parent machine's state node, or as a `:spawn-all` child.
         The wrapper runs the request on entry and finishes in a :final?
         :succeeded / :failed leaf carrying the value under :rf/result;
         a :spawn parent also receives `[<parent-id> [:succeeded value]]`
         (or :failed)."
   :initial :requesting
   :states
   {:requesting
    ;; Initial-state `:entry` actions fire on spawn as part of the
    ;; bootstrap cascade — the canonical re-frame2 shape for "do this
    ;; when the actor first runs".
    {:entry :fire-request
     :on    {:rf.http/succeeded  {:target :succeeded :action :record-value}
             :rf.http/failed     {:target :failed    :action :record-failure}}}

    ;; Spec 005 §Child completion protocol — `:meta {:terminal? true}` is not
    ;; a synonym for `:final?`, and a join resolves only on `:final?`.
    :succeeded
    {:entry      :dispatch-done
     :final?     true
     :output-key :rf/result}

    :failed
    {:entry      :dispatch-error
     :final?     true
     :error?     true
     :output-key :rf/result}}

   :actions
   {:fire-request
    (fn [{data :data}]
      ;; Build the args map for the underlying fx from whatever the
      ;; user passed through the parent's :spawn :data. Strip the
      ;; framework-reserved `:rf/*` keys; pass through every other
      ;; documented arg (Spec 014 §The args map) so the wrapper is a
      ;; transparent envelope around the fx surface.
      (let [self-id   (:rf/self-id data)
            fx-args   (-> data
                          (dissoc :rf/self-id :rf/parent-id :rf/invoke-id :rf/join-child)
                          (assoc :on-success [self-id [:rf.http/succeeded]]
                                 :on-failure [self-id [:rf.http/failed]]))]
        {:fx [[:rf.http/managed fx-args]]}))

    ;; `:rf/result` is what `:output-key` hands a join AND what the terminal
    ;; `:entry` hands a `:spawn` parent, so both parents see one value.
    :record-value
    (fn [{data :data [_ reply] :event}]
      {:data (assoc data :rf/result (:value reply))})

    :record-failure
    (fn [{data :data [_ reply] :event}]
      ;; rf2-ibksxg — the reply payload is the canonical envelope; the
      ;; classified `:rf.http/*` failure map rides under `:error`
      ;; (`:status :error` / `:cancelled`), not the retired `:failure`.
      {:data (assoc data :rf/result (:error reply))})

    :dispatch-done
    (fn [{data :data}]
      (when-let [parent-id (parent-to-notify data)]
        {:fx [[:dispatch [parent-id [:succeeded (:rf/result data)]]]]}))

    :dispatch-error
    (fn [{data :data}]
      (when-let [parent-id (parent-to-notify data)]
        {:fx [[:dispatch [parent-id [:failed (:rf/result data)]]]]}))}})

(defn register-managed-machine!
  "Register the `:rf.http/managed` machine-shape wrapper via the
  `:machines/reg-machine` late-bind hook. Returns the registered
  machine-id on success, or nil if the machines artefact is not on the
  classpath (in which case the existing fx-only surface is unaffected)."
  []
  (when-let [reg-machine* (rf.late-bind/get-fn :machines/reg-machine)]
    (reg-machine* :rf.http/managed (http-managed-machine-spec))
    :rf.http/managed))
