(ns day8.re-frame2-machines-viz.mermaid-public-smoke-test
  "The consumer-side seam: requiring the public `mermaid` ns alone yields a
  Mermaid string, with the documented option defaults. Edge-case coverage
  lives in `day8.re-frame2-machines-viz.mermaid-cljs-test`."
  (:require [clojure.test :refer [deftest is testing]]
            [clojure.string :as str]
            [day8.re-frame2-machines-viz.mermaid :as mermaid]))

(def ^:private definition
  {:initial :idle
   :states  {:idle    {:on {:start :loading}}
             :loading {:on {:done :idle}}}})

(deftest public-emit-from-outside-the-ns
  (testing "by default the diagram is fenced and carries the generated-by caveat"
    (let [out (mermaid/emit definition)]
      (is (str/starts-with? out "```mermaid"))
      (is (str/ends-with? out "```"))
      (is (str/includes? out "%% Generated by day8.re-frame2-machines-viz.mermaid"))
      (is (str/includes? out "stateDiagram-v2"))
      (is (str/includes? out "[*] --> idle"))
      (is (str/includes? out "idle --> loading : start")))))

(deftest public-emit-honours-option-map
  (testing ":fenced? false and :header-comment? false leave the bare diagram"
    (let [plain (mermaid/emit definition {:fenced? false :header-comment? false})]
      (is (str/starts-with? plain "stateDiagram-v2"))
      (is (not (str/includes? plain "```")))
      (is (not (str/includes? plain "%%"))))))
