(ns day8.re-frame2-machines-viz.mermaid-cljs-test
  "Pure-data tests for the Mermaid `stateDiagram-v2` exporter
  (rf2-deo2i). The `_cljs_test` naming follows the convention from
  tools/causa/test/ — Cognitect's test-runner picks the ns up via
  the default `.*-test$` regex, and Shadow's `:node-test` build (to
  be wired in a later bead) picks it up via `cljs-test$`."
  (:require [clojure.test  :refer [deftest is testing]]
            [clojure.string :as str]
            [day8.re-frame2-machines-viz.mermaid :as m]))

;; -----------------------------------------------------------------------------
;; Fixtures — small, hand-curated machine definitions per Spec 005
;; §Transition table grammar.

(def idle-loading-success-error
  "The canonical small machine from the bead description: idle →
  loading → success / error. Two final states."
  {:initial :idle
   :states  {:idle    {:on {:start :loading}}
             :loading {:on {:ok :success :err :failed}}
             :success {:final? true}
             :failed  {:final? true}}})

(def compound-machine
  "A compound machine with one nested region — exercises Mermaid's
  `state X { ... }` block."
  {:initial :unauth
   :states  {:unauth        {:on {:login :authenticated}}
             :authenticated {:initial :browsing
                             :states  {:browsing {:on {:checkout :paying}}
                                       :paying   {:on {:done :browsing}}}
                             :on      {:logout :unauth}}}})

(def namespaced-ids-machine
  "Machine using namespaced and hyphenated ids — exercises
  sanitise-id."
  {:initial :auth/idle
   :states  {:auth/idle      {:on {:rf/load :auth/loading}}
             :auth/loading   {:on {:done :auth/idle}}}})

;; -----------------------------------------------------------------------------
;; Tests

(deftest emit-returns-fenced-block-by-default
  (testing "default output is wrapped in a ```mermaid fence"
    (let [out (m/emit idle-loading-success-error)]
      (is (str/starts-with? out "```mermaid\n"))
      (is (str/ends-with?   out "\n```")))))

(deftest emit-unfenced-omits-the-fence
  (testing ":fenced? false strips the markdown fence"
    (let [out (m/emit idle-loading-success-error {:fenced? false})]
      (is (not (str/includes? out "```")))
      (is (str/includes? out "stateDiagram-v2")))))

(deftest emit-includes-stateDiagram-v2-header
  (testing "every emit starts the diagram with `stateDiagram-v2`"
    (is (str/includes? (m/emit idle-loading-success-error)
                       "stateDiagram-v2"))))

(deftest emit-renders-initial-state-edge
  (testing "[*] --> initial-state appears at the top of the diagram"
    (is (str/includes? (m/emit idle-loading-success-error)
                       "[*] --> idle"))))

(deftest emit-renders-transitions
  (testing "every statically-resolvable transition appears as an edge"
    (let [out (m/emit idle-loading-success-error)]
      (is (str/includes? out "idle --> loading : start"))
      (is (str/includes? out "loading --> success : ok"))
      (is (str/includes? out "loading --> failed : err")))))

(deftest emit-renders-final-state-edges
  (testing ":final? true states render `state --> [*]`"
    (let [out (m/emit idle-loading-success-error)]
      (is (str/includes? out "success --> [*]"))
      (is (str/includes? out "failed --> [*]")))))

(deftest emit-includes-omission-caveat-by-default
  (testing "the `:after` + `:invoke-all` omission caveat lands at the top"
    (let [out (m/emit idle-loading-success-error)]
      (is (str/includes? out "%% Generated by re-frame2-machines-viz"))
      (is (str/includes? out ":after rings + :invoke-all rows omitted")))))

(deftest emit-can-suppress-header-comment
  (testing ":header-comment? false drops the %% caveat lines"
    (let [out (m/emit idle-loading-success-error {:header-comment? false})]
      (is (not (str/includes? out "%%"))))))

(deftest emit-renders-compound-state-block
  (testing "compound states render as `state X { ... }` with inner [*] --> initial"
    (let [out (m/emit compound-machine)]
      (is (str/includes? out "state authenticated {"))
      (is (str/includes? out "[*] --> browsing"))
      (is (str/includes? out "}")))))

(deftest emit-renders-cross-region-transitions
  (testing "transitions across compound boundaries render as flat edges"
    (let [out (m/emit compound-machine)]
      ;; unauth --> authenticated (top-level edge)
      (is (str/includes? out "unauth --> authenticated : login"))
      ;; authenticated --> unauth (compound-state-out edge, on the
      ;; compound state's `:on` map)
      (is (str/includes? out "authenticated --> unauth : logout"))
      ;; nested edges still emit
      (is (str/includes? out "browsing --> paying : checkout"))
      (is (str/includes? out "paying --> browsing : done")))))

(deftest emit-sanitises-namespaced-and-hyphenated-ids
  (testing "namespaced + hyphenated keywords map to underscore-joined ids"
    (let [out (m/emit namespaced-ids-machine)]
      ;; :auth/idle → auth_idle, :auth/loading → auth_loading
      (is (str/includes? out "auth_idle"))
      (is (str/includes? out "auth_loading"))
      ;; :rf/load → "rf/load" as the edge label (sanitise-label keeps
      ;; the slash; only sanitise-id strips it)
      (is (str/includes? out "auth_idle --> auth_loading : rf/load")))))

(deftest emit-validates-definition
  (testing "definitions missing :initial or :states throw :invalid-definition"
    (is (thrown? #?(:clj clojure.lang.ExceptionInfo
                    :cljs ExceptionInfo)
                 (m/emit {})))
    (is (thrown? #?(:clj clojure.lang.ExceptionInfo
                    :cljs ExceptionInfo)
                 (m/emit {:initial :idle})))
    (is (thrown? #?(:clj clojure.lang.ExceptionInfo
                    :cljs ExceptionInfo)
                 (m/emit {:initial :idle :states {}})))))

(deftest emit-drops-wildcard-transitions
  (testing ":* wildcard transitions don't render (Mermaid can't express them)"
    (let [m   {:initial :a
               :states  {:a {:on {:* :b
                                  :go :b}}
                         :b {}}}
          out (m/emit m)]
      ;; The `:go` edge is present
      (is (str/includes? out "a --> b : go"))
      ;; The wildcard is not rendered as its own edge: there is
      ;; exactly one `a --> b` edge in the output (the `:go` one).
      (is (= 1 (count (re-seq #"a --> b" out))))
      (is (not (str/includes? out " : *"))))))

(deftest emit-handles-map-shaped-transition-spec
  (testing "map-shaped transition specs with :target render their target"
    (let [m   {:initial :a
               :states  {:a {:on {:go {:target :b
                                       :action :record
                                       :guard  :ready?}}}
                         :b {}}}
          out (m/emit m)]
      (is (str/includes? out "a --> b : go")))))

(deftest emit-drops-target-less-transitions
  (testing "internal / fn-shaped transitions without a resolvable :target are dropped"
    (let [m   {:initial :a
               :states  {:a {:on {:go     {:action :record}        ;; no :target
                                  :reset  (fn [_ _] {:state :a})}} ;; fn-shaped
                         :b {}}}
          out (m/emit m)]
      ;; Neither :go nor :reset can be rendered without a known target;
      ;; both should be silently dropped (the topology stays valid).
      (is (not (str/includes? out "a --> "))))))

;; -----------------------------------------------------------------------------
;; Smoke: round-trip the bead's example through emit + verify the
;; shape a GitHub reader would see.

(deftest emit-smoke-round-trip
  (testing "the canonical bead fixture emits a plausible Mermaid block"
    (let [out (m/emit idle-loading-success-error)]
      ;; Has the fence
      (is (str/starts-with? out "```mermaid"))
      ;; Has the header
      (is (str/includes? out "stateDiagram-v2"))
      ;; Has the initial-edge
      (is (str/includes? out "[*] --> idle"))
      ;; Has every transition
      (is (str/includes? out "idle --> loading : start"))
      (is (str/includes? out "loading --> success : ok"))
      (is (str/includes? out "loading --> failed : err"))
      ;; Has both terminal edges
      (is (str/includes? out "success --> [*]"))
      (is (str/includes? out "failed --> [*]"))
      ;; Mentions the omission caveat
      (is (str/includes? out ":after rings + :invoke-all rows omitted"))
      ;; Closes the fence
      (is (str/ends-with? out "```")))))
